export interface CountyResult {
  county: string;
  state: string;
  stateCode: string;
  inmateUrl: string;
  urlNote?: string;
}

// ZIP3 prefix → county/region lookup. Covers ~200 major prefixes (top metro areas).
// For unrecognized prefixes, fall back to state-level VINELink via the first digit.
const ZIP3_LOOKUP: Record<string, CountyResult> = {
  // New York
  "100": { county: "New York County (Manhattan)", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "101": { county: "New York County (Manhattan)", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "102": { county: "New York County (Manhattan)", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "103": { county: "Richmond County (Staten Island)", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "104": { county: "Bronx County", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "105": { county: "Westchester County", state: "New York", stateCode: "NY", inmateUrl: "https://vinelink.vineapps.com/search/NY/Person" },
  "106": { county: "Westchester County", state: "New York", stateCode: "NY", inmateUrl: "https://vinelink.vineapps.com/search/NY/Person" },
  "110": { county: "Queens County", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "111": { county: "Queens County", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "112": { county: "Kings County (Brooklyn)", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "113": { county: "Kings County (Brooklyn)", state: "New York", stateCode: "NY", inmateUrl: "https://a073-ils.nyc.gov/inmatelookup/pages/home/home.jsf" },
  "114": { county: "Nassau County", state: "New York", stateCode: "NY", inmateUrl: "https://vinelink.vineapps.com/search/NY/Person" },
  "115": { county: "Nassau County", state: "New York", stateCode: "NY", inmateUrl: "https://vinelink.vineapps.com/search/NY/Person" },
  "116": { county: "Nassau/Suffolk County", state: "New York", stateCode: "NY", inmateUrl: "https://vinelink.vineapps.com/search/NY/Person" },
  "117": { county: "Suffolk County", state: "New York", stateCode: "NY", inmateUrl: "https://vinelink.vineapps.com/search/NY/Person" },
  "118": { county: "Suffolk County", state: "New York", stateCode: "NY", inmateUrl: "https://vinelink.vineapps.com/search/NY/Person" },
  "119": { county: "Suffolk County", state: "New York", stateCode: "NY", inmateUrl: "https://vinelink.vineapps.com/search/NY/Person" },
  // New Jersey
  "070": { county: "Essex County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  "071": { county: "Essex County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  "072": { county: "Hudson County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  "073": { county: "Hudson/Bergen County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  "074": { county: "Passaic County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  "077": { county: "Middlesex County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  "080": { county: "Burlington County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  "081": { county: "Camden County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  "085": { county: "Mercer County", state: "New Jersey", stateCode: "NJ", inmateUrl: "https://www.njinmateinfo.com/" },
  // Pennsylvania
  "190": { county: "Philadelphia County", state: "Pennsylvania", stateCode: "PA", inmateUrl: "https://www.phila.gov/departments/philadelphia-department-of-prisons/inmate-locator/", urlNote: "City of Philadelphia Department of Prisons" },
  "191": { county: "Philadelphia County", state: "Pennsylvania", stateCode: "PA", inmateUrl: "https://www.phila.gov/departments/philadelphia-department-of-prisons/inmate-locator/" },
  "192": { county: "Montgomery County", state: "Pennsylvania", stateCode: "PA", inmateUrl: "https://vinelink.vineapps.com/search/PA/Person" },
  "193": { county: "Bucks County", state: "Pennsylvania", stateCode: "PA", inmateUrl: "https://vinelink.vineapps.com/search/PA/Person" },
  "195": { county: "Delaware County", state: "Pennsylvania", stateCode: "PA", inmateUrl: "https://vinelink.vineapps.com/search/PA/Person" },
  "152": { county: "Allegheny County (Pittsburgh)", state: "Pennsylvania", stateCode: "PA", inmateUrl: "https://vinelink.vineapps.com/search/PA/Person" },
  "153": { county: "Allegheny County (Pittsburgh)", state: "Pennsylvania", stateCode: "PA", inmateUrl: "https://vinelink.vineapps.com/search/PA/Person" },
  // Delaware
  "197": { county: "New Castle County", state: "Delaware", stateCode: "DE", inmateUrl: "https://vinelink.vineapps.com/search/DE/Person" },
  "198": { county: "New Castle County", state: "Delaware", stateCode: "DE", inmateUrl: "https://vinelink.vineapps.com/search/DE/Person" },
  // Maryland
  "200": { county: "District of Columbia", state: "Washington D.C.", stateCode: "DC", inmateUrl: "https://vinelink.vineapps.com/search/DC/Person" },
  "201": { county: "District of Columbia", state: "Washington D.C.", stateCode: "DC", inmateUrl: "https://vinelink.vineapps.com/search/DC/Person" },
  "202": { county: "District of Columbia", state: "Washington D.C.", stateCode: "DC", inmateUrl: "https://vinelink.vineapps.com/search/DC/Person" },
  "203": { county: "Montgomery County", state: "Maryland", stateCode: "MD", inmateUrl: "https://vinelink.vineapps.com/search/MD/Person" },
  "204": { county: "Montgomery County", state: "Maryland", stateCode: "MD", inmateUrl: "https://vinelink.vineapps.com/search/MD/Person" },
  "205": { county: "Prince George's County", state: "Maryland", stateCode: "MD", inmateUrl: "https://vinelink.vineapps.com/search/MD/Person" },
  "206": { county: "Prince George's County", state: "Maryland", stateCode: "MD", inmateUrl: "https://vinelink.vineapps.com/search/MD/Person" },
  "207": { county: "Prince George's/Montgomery County", state: "Maryland", stateCode: "MD", inmateUrl: "https://vinelink.vineapps.com/search/MD/Person" },
  "210": { county: "Baltimore City", state: "Maryland", stateCode: "MD", inmateUrl: "https://vinelink.vineapps.com/search/MD/Person" },
  "211": { county: "Baltimore City", state: "Maryland", stateCode: "MD", inmateUrl: "https://vinelink.vineapps.com/search/MD/Person" },
  "212": { county: "Baltimore County", state: "Maryland", stateCode: "MD", inmateUrl: "https://vinelink.vineapps.com/search/MD/Person" },
  // Virginia
  "220": { county: "Arlington County / Alexandria City", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "221": { county: "Fairfax County", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "222": { county: "Fairfax County", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "223": { county: "Fairfax/Prince William County", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "226": { county: "Harrisonburg City / Rockingham County", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "229": { county: "Charlottesville / Albemarle County", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "232": { county: "Richmond City / Henrico County", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "235": { county: "Norfolk City / Virginia Beach", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "236": { county: "Norfolk City", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  "238": { county: "Virginia Beach City", state: "Virginia", stateCode: "VA", inmateUrl: "https://vadoc.virginia.gov/offenders/locator/" },
  // North Carolina
  "270": { county: "Forsyth County (Winston-Salem)", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  "271": { county: "Guilford County (Greensboro)", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  "272": { county: "Guilford County (Greensboro)", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  "273": { county: "Durham County", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  "274": { county: "Wake County (Raleigh)", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  "275": { county: "Wake County (Raleigh)", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  "280": { county: "Mecklenburg County (Charlotte)", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  "281": { county: "Mecklenburg County (Charlotte)", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  "282": { county: "Union/Cabarrus County", state: "North Carolina", stateCode: "NC", inmateUrl: "https://webapps.doc.state.nc.us/opi/offendersearch.do" },
  // South Carolina
  "290": { county: "Richland County (Columbia)", state: "South Carolina", stateCode: "SC", inmateUrl: "https://vinelink.vineapps.com/search/SC/Person" },
  "292": { county: "Lexington County", state: "South Carolina", stateCode: "SC", inmateUrl: "https://vinelink.vineapps.com/search/SC/Person" },
  "293": { county: "Greenville County", state: "South Carolina", stateCode: "SC", inmateUrl: "https://vinelink.vineapps.com/search/SC/Person" },
  "295": { county: "Berkeley/Charleston County", state: "South Carolina", stateCode: "SC", inmateUrl: "https://vinelink.vineapps.com/search/SC/Person" },
  // Georgia
  "300": { county: "Fulton County (Atlanta)", state: "Georgia", stateCode: "GA", inmateUrl: "https://vinelink.vineapps.com/search/GA/Person" },
  "301": { county: "Fulton County (Atlanta)", state: "Georgia", stateCode: "GA", inmateUrl: "https://vinelink.vineapps.com/search/GA/Person" },
  "302": { county: "Fulton County (Atlanta)", state: "Georgia", stateCode: "GA", inmateUrl: "https://vinelink.vineapps.com/search/GA/Person" },
  "303": { county: "DeKalb County", state: "Georgia", stateCode: "GA", inmateUrl: "https://vinelink.vineapps.com/search/GA/Person" },
  "304": { county: "Cobb County (Marietta)", state: "Georgia", stateCode: "GA", inmateUrl: "https://vinelink.vineapps.com/search/GA/Person" },
  "305": { county: "Cobb County", state: "Georgia", stateCode: "GA", inmateUrl: "https://vinelink.vineapps.com/search/GA/Person" },
  "306": { county: "Gwinnett County", state: "Georgia", stateCode: "GA", inmateUrl: "https://vinelink.vineapps.com/search/GA/Person" },
  "307": { county: "Gwinnett County", state: "Georgia", stateCode: "GA", inmateUrl: "https://vinelink.vineapps.com/search/GA/Person" },
  // Florida
  "320": { county: "Leon County (Tallahassee)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "321": { county: "Brevard County (Space Coast)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "322": { county: "Duval County (Jacksonville)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "323": { county: "Duval County (Jacksonville)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "324": { county: "Duval/Nassau County", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "325": { county: "Alachua County (Gainesville)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "326": { county: "Alachua/Marion County", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "327": { county: "Seminole County (Sanford)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "328": { county: "Orange County (Orlando)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "329": { county: "Orange County (Orlando)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "330": { county: "Miami-Dade County", state: "Florida", stateCode: "FL", inmateUrl: "https://www.miamiinmateinfo.com/", urlNote: "Miami-Dade Corrections inmate search" },
  "331": { county: "Miami-Dade County", state: "Florida", stateCode: "FL", inmateUrl: "https://www.miamiinmateinfo.com/" },
  "332": { county: "Miami-Dade County", state: "Florida", stateCode: "FL", inmateUrl: "https://www.miamiinmateinfo.com/" },
  "333": { county: "Broward County (Fort Lauderdale)", state: "Florida", stateCode: "FL", inmateUrl: "https://www.sheriff.org/BSO_Unit/WEB_Inmate/Pages/home.aspx", urlNote: "Broward Sheriff's Office" },
  "334": { county: "Palm Beach County", state: "Florida", stateCode: "FL", inmateUrl: "https://apps.co.palm-beach.fl.us/pbso/inmate_search_form.asp", urlNote: "Palm Beach County Sheriff" },
  "335": { county: "Hillsborough County (Tampa)", state: "Florida", stateCode: "FL", inmateUrl: "https://www.hillsboroughcounty.org/en/residents/public-safety/jail-information/inmate-search" },
  "336": { county: "Hillsborough County (Tampa)", state: "Florida", stateCode: "FL", inmateUrl: "https://www.hillsboroughcounty.org/en/residents/public-safety/jail-information/inmate-search" },
  "337": { county: "Hillsborough County (Tampa)", state: "Florida", stateCode: "FL", inmateUrl: "https://www.hillsboroughcounty.org/en/residents/public-safety/jail-information/inmate-search" },
  "338": { county: "Manatee/Sarasota County", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "339": { county: "Lee County (Fort Myers)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "341": { county: "Collier County (Naples)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "346": { county: "Pasco County (New Port Richey)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  "347": { county: "Osceola County (Kissimmee)", state: "Florida", stateCode: "FL", inmateUrl: "https://vinelink.vineapps.com/search/FL/Person" },
  // Alabama
  "350": { county: "Jefferson County (Birmingham)", state: "Alabama", stateCode: "AL", inmateUrl: "https://vinelink.vineapps.com/search/AL/Person" },
  "351": { county: "Jefferson County (Birmingham)", state: "Alabama", stateCode: "AL", inmateUrl: "https://vinelink.vineapps.com/search/AL/Person" },
  "359": { county: "Mobile County", state: "Alabama", stateCode: "AL", inmateUrl: "https://vinelink.vineapps.com/search/AL/Person" },
  "360": { county: "Montgomery County", state: "Alabama", stateCode: "AL", inmateUrl: "https://vinelink.vineapps.com/search/AL/Person" },
  // Tennessee
  "370": { county: "Davidson County (Nashville)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  "371": { county: "Davidson County (Nashville)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  "372": { county: "Davidson County (Nashville)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  "374": { county: "Hamilton County (Chattanooga)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  "376": { county: "Knox County (Knoxville)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  "377": { county: "Knox County (Knoxville)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  "378": { county: "Knox County (Knoxville)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  "380": { county: "Shelby County (Memphis)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  "381": { county: "Shelby County (Memphis)", state: "Tennessee", stateCode: "TN", inmateUrl: "https://vinelink.vineapps.com/search/TN/Person" },
  // Ohio
  "430": { county: "Franklin County (Columbus)", state: "Ohio", stateCode: "OH", inmateUrl: "https://sheriff.franklincountyohio.gov/corrections/inmate-search" },
  "431": { county: "Franklin County (Columbus)", state: "Ohio", stateCode: "OH", inmateUrl: "https://sheriff.franklincountyohio.gov/corrections/inmate-search" },
  "432": { county: "Franklin County (Columbus)", state: "Ohio", stateCode: "OH", inmateUrl: "https://sheriff.franklincountyohio.gov/corrections/inmate-search" },
  "440": { county: "Cuyahoga County (Cleveland)", state: "Ohio", stateCode: "OH", inmateUrl: "https://cuyahogasheriff.com/law-enforcement/corrections/inmate-search/" },
  "441": { county: "Cuyahoga County (Cleveland)", state: "Ohio", stateCode: "OH", inmateUrl: "https://cuyahogasheriff.com/law-enforcement/corrections/inmate-search/" },
  "442": { county: "Summit County (Akron)", state: "Ohio", stateCode: "OH", inmateUrl: "https://vinelink.vineapps.com/search/OH/Person" },
  "450": { county: "Hamilton County (Cincinnati)", state: "Ohio", stateCode: "OH", inmateUrl: "https://vinelink.vineapps.com/search/OH/Person" },
  "451": { county: "Hamilton County (Cincinnati)", state: "Ohio", stateCode: "OH", inmateUrl: "https://vinelink.vineapps.com/search/OH/Person" },
  "452": { county: "Hamilton County (Cincinnati)", state: "Ohio", stateCode: "OH", inmateUrl: "https://vinelink.vineapps.com/search/OH/Person" },
  // Indiana
  "460": { county: "Marion County (Indianapolis)", state: "Indiana", stateCode: "IN", inmateUrl: "https://vinelink.vineapps.com/search/IN/Person" },
  "461": { county: "Marion County (Indianapolis)", state: "Indiana", stateCode: "IN", inmateUrl: "https://vinelink.vineapps.com/search/IN/Person" },
  "462": { county: "Marion County (Indianapolis)", state: "Indiana", stateCode: "IN", inmateUrl: "https://vinelink.vineapps.com/search/IN/Person" },
  // Michigan
  "480": { county: "Wayne County (Detroit)", state: "Michigan", stateCode: "MI", inmateUrl: "https://mdocweb.state.mi.us/otis2/otis2.aspx", urlNote: "State lookup; county jail: wccorrections.com" },
  "481": { county: "Wayne County (Detroit)", state: "Michigan", stateCode: "MI", inmateUrl: "https://mdocweb.state.mi.us/otis2/otis2.aspx" },
  "482": { county: "Wayne County (Detroit) / Oakland County", state: "Michigan", stateCode: "MI", inmateUrl: "https://mdocweb.state.mi.us/otis2/otis2.aspx" },
  "483": { county: "Oakland County", state: "Michigan", stateCode: "MI", inmateUrl: "https://mdocweb.state.mi.us/otis2/otis2.aspx" },
  "484": { county: "Macomb County", state: "Michigan", stateCode: "MI", inmateUrl: "https://mdocweb.state.mi.us/otis2/otis2.aspx" },
  "491": { county: "Kent County (Grand Rapids)", state: "Michigan", stateCode: "MI", inmateUrl: "https://mdocweb.state.mi.us/otis2/otis2.aspx" },
  "493": { county: "Ingham County (Lansing)", state: "Michigan", stateCode: "MI", inmateUrl: "https://mdocweb.state.mi.us/otis2/otis2.aspx" },
  // Illinois
  "606": { county: "Cook County (Chicago)", state: "Illinois", stateCode: "IL", inmateUrl: "https://www2.cookcountysheriff.org/search2/", urlNote: "Cook County Sheriff inmate search" },
  "607": { county: "Cook County (Chicago)", state: "Illinois", stateCode: "IL", inmateUrl: "https://www2.cookcountysheriff.org/search2/" },
  "608": { county: "Cook County (Chicago)", state: "Illinois", stateCode: "IL", inmateUrl: "https://www2.cookcountysheriff.org/search2/" },
  "609": { county: "DuPage County", state: "Illinois", stateCode: "IL", inmateUrl: "https://vinelink.vineapps.com/search/IL/Person" },
  "610": { county: "Cook County (suburbs)", state: "Illinois", stateCode: "IL", inmateUrl: "https://www2.cookcountysheriff.org/search2/" },
  "611": { county: "Kane County", state: "Illinois", stateCode: "IL", inmateUrl: "https://vinelink.vineapps.com/search/IL/Person" },
  "616": { county: "Lake County", state: "Illinois", stateCode: "IL", inmateUrl: "https://vinelink.vineapps.com/search/IL/Person" },
  "617": { county: "Lake County", state: "Illinois", stateCode: "IL", inmateUrl: "https://vinelink.vineapps.com/search/IL/Person" },
  "618": { county: "Cook County (south suburbs)", state: "Illinois", stateCode: "IL", inmateUrl: "https://www2.cookcountysheriff.org/search2/" },
  "619": { county: "Cook County (south suburbs)", state: "Illinois", stateCode: "IL", inmateUrl: "https://www2.cookcountysheriff.org/search2/" },
  "620": { county: "St. Clair County (E. St. Louis)", state: "Illinois", stateCode: "IL", inmateUrl: "https://vinelink.vineapps.com/search/IL/Person" },
  // Minnesota
  "550": { county: "Ramsey County (St. Paul)", state: "Minnesota", stateCode: "MN", inmateUrl: "https://vinelink.vineapps.com/search/MN/Person" },
  "551": { county: "Ramsey County / Dakota County", state: "Minnesota", stateCode: "MN", inmateUrl: "https://vinelink.vineapps.com/search/MN/Person" },
  "554": { county: "Hennepin County (Minneapolis)", state: "Minnesota", stateCode: "MN", inmateUrl: "https://vinelink.vineapps.com/search/MN/Person" },
  "555": { county: "Hennepin County (Minneapolis)", state: "Minnesota", stateCode: "MN", inmateUrl: "https://vinelink.vineapps.com/search/MN/Person" },
  "563": { county: "Olmsted County (Rochester)", state: "Minnesota", stateCode: "MN", inmateUrl: "https://vinelink.vineapps.com/search/MN/Person" },
  // Wisconsin
  "530": { county: "Milwaukee County", state: "Wisconsin", stateCode: "WI", inmateUrl: "https://appsdoc.wi.gov/lop/home.do" },
  "531": { county: "Milwaukee County", state: "Wisconsin", stateCode: "WI", inmateUrl: "https://appsdoc.wi.gov/lop/home.do" },
  "532": { county: "Milwaukee County (suburbs)", state: "Wisconsin", stateCode: "WI", inmateUrl: "https://appsdoc.wi.gov/lop/home.do" },
  "537": { county: "Dane County (Madison)", state: "Wisconsin", stateCode: "WI", inmateUrl: "https://appsdoc.wi.gov/lop/home.do" },
  // Missouri / Kansas City
  "631": { county: "St. Louis City", state: "Missouri", stateCode: "MO", inmateUrl: "https://vinelink.vineapps.com/search/MO/Person" },
  "632": { county: "St. Louis City", state: "Missouri", stateCode: "MO", inmateUrl: "https://vinelink.vineapps.com/search/MO/Person" },
  "633": { county: "St. Louis County", state: "Missouri", stateCode: "MO", inmateUrl: "https://vinelink.vineapps.com/search/MO/Person" },
  "640": { county: "Jackson County (Kansas City)", state: "Missouri", stateCode: "MO", inmateUrl: "https://vinelink.vineapps.com/search/MO/Person" },
  "641": { county: "Jackson County (Kansas City)", state: "Missouri", stateCode: "MO", inmateUrl: "https://vinelink.vineapps.com/search/MO/Person" },
  // Kansas
  "660": { county: "Johnson County (Overland Park)", state: "Kansas", stateCode: "KS", inmateUrl: "https://vinelink.vineapps.com/search/KS/Person" },
  "662": { county: "Wyandotte County (Kansas City, KS)", state: "Kansas", stateCode: "KS", inmateUrl: "https://vinelink.vineapps.com/search/KS/Person" },
  "672": { county: "Sedgwick County (Wichita)", state: "Kansas", stateCode: "KS", inmateUrl: "https://vinelink.vineapps.com/search/KS/Person" },
  // Texas
  "750": { county: "Dallas County", state: "Texas", stateCode: "TX", inmateUrl: "https://www.dallascounty.org/departments/dallasdetention/inmate-search.php", urlNote: "Dallas County Detention Management" },
  "751": { county: "Dallas County", state: "Texas", stateCode: "TX", inmateUrl: "https://www.dallascounty.org/departments/dallasdetention/inmate-search.php" },
  "752": { county: "Dallas County", state: "Texas", stateCode: "TX", inmateUrl: "https://www.dallascounty.org/departments/dallasdetention/inmate-search.php" },
  "753": { county: "Dallas County", state: "Texas", stateCode: "TX", inmateUrl: "https://www.dallascounty.org/departments/dallasdetention/inmate-search.php" },
  "754": { county: "Dallas County", state: "Texas", stateCode: "TX", inmateUrl: "https://www.dallascounty.org/departments/dallasdetention/inmate-search.php" },
  "760": { county: "Tarrant County (Fort Worth)", state: "Texas", stateCode: "TX", inmateUrl: "https://www.tcso.org/jailrecords/", urlNote: "Tarrant County Sheriff's Office" },
  "761": { county: "Tarrant County (Fort Worth)", state: "Texas", stateCode: "TX", inmateUrl: "https://www.tcso.org/jailrecords/" },
  "762": { county: "Tarrant County (Fort Worth)", state: "Texas", stateCode: "TX", inmateUrl: "https://www.tcso.org/jailrecords/" },
  "770": { county: "Harris County (Houston)", state: "Texas", stateCode: "TX", inmateUrl: "https://jaildata.harriscountytx.gov/", urlNote: "Harris County Sheriff Jail Information" },
  "771": { county: "Harris County (Houston)", state: "Texas", stateCode: "TX", inmateUrl: "https://jaildata.harriscountytx.gov/" },
  "772": { county: "Harris County (Houston)", state: "Texas", stateCode: "TX", inmateUrl: "https://jaildata.harriscountytx.gov/" },
  "773": { county: "Harris County (Houston)", state: "Texas", stateCode: "TX", inmateUrl: "https://jaildata.harriscountytx.gov/" },
  "774": { county: "Harris County (Houston)", state: "Texas", stateCode: "TX", inmateUrl: "https://jaildata.harriscountytx.gov/" },
  "775": { county: "Fort Bend County", state: "Texas", stateCode: "TX", inmateUrl: "https://vinelink.vineapps.com/search/TX/Person" },
  "782": { county: "Bexar County (San Antonio)", state: "Texas", stateCode: "TX", inmateUrl: "https://www.bexarcounty.gov/CorrectionalHealth/Pages/Inmate-Lookup.aspx", urlNote: "Bexar County jail lookup" },
  "783": { county: "Bexar County (San Antonio)", state: "Texas", stateCode: "TX", inmateUrl: "https://www.bexarcounty.gov/CorrectionalHealth/Pages/Inmate-Lookup.aspx" },
  "784": { county: "Bexar County (San Antonio)", state: "Texas", stateCode: "TX", inmateUrl: "https://www.bexarcounty.gov/CorrectionalHealth/Pages/Inmate-Lookup.aspx" },
  "785": { county: "Bexar County (San Antonio)", state: "Texas", stateCode: "TX", inmateUrl: "https://www.bexarcounty.gov/CorrectionalHealth/Pages/Inmate-Lookup.aspx" },
  "786": { county: "Travis County (Austin)", state: "Texas", stateCode: "TX", inmateUrl: "https://vinelink.vineapps.com/search/TX/Person" },
  "787": { county: "Travis County (Austin)", state: "Texas", stateCode: "TX", inmateUrl: "https://vinelink.vineapps.com/search/TX/Person" },
  "788": { county: "Travis County (Austin)", state: "Texas", stateCode: "TX", inmateUrl: "https://vinelink.vineapps.com/search/TX/Person" },
  "790": { county: "Lubbock County", state: "Texas", stateCode: "TX", inmateUrl: "https://vinelink.vineapps.com/search/TX/Person" },
  "795": { county: "El Paso County", state: "Texas", stateCode: "TX", inmateUrl: "https://vinelink.vineapps.com/search/TX/Person" },
  "796": { county: "El Paso County", state: "Texas", stateCode: "TX", inmateUrl: "https://vinelink.vineapps.com/search/TX/Person" },
  "797": { county: "El Paso County", state: "Texas", stateCode: "TX", inmateUrl: "https://vinelink.vineapps.com/search/TX/Person" },
  // Colorado
  "800": { county: "Denver County", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Detention-Management/Current-Inmates", urlNote: "Denver City/County" },
  "801": { county: "Denver County", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Detention-Management/Current-Inmates" },
  "802": { county: "Denver County", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Detention-Management/Current-Inmates" },
  "803": { county: "Jefferson / Arapahoe County", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.colorado.gov/apps/offender/public/#/" },
  "804": { county: "Adams County", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.colorado.gov/apps/offender/public/#/" },
  "805": { county: "Arapahoe County", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.colorado.gov/apps/offender/public/#/" },
  "806": { county: "El Paso County (Colorado Springs)", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.colorado.gov/apps/offender/public/#/" },
  "807": { county: "Jefferson County (Lakewood)", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.colorado.gov/apps/offender/public/#/" },
  "808": { county: "Pueblo County", state: "Colorado", stateCode: "CO", inmateUrl: "https://www.colorado.gov/apps/offender/public/#/" },
  // Arizona
  "850": { county: "Maricopa County (Phoenix)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://www.mcso.org/Jailinfo/InmateSearch", urlNote: "Maricopa County Sheriff's Office" },
  "851": { county: "Maricopa County (Phoenix)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://www.mcso.org/Jailinfo/InmateSearch" },
  "852": { county: "Maricopa County (Phoenix)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://www.mcso.org/Jailinfo/InmateSearch" },
  "853": { county: "Maricopa County (Phoenix)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://www.mcso.org/Jailinfo/InmateSearch" },
  "854": { county: "Maricopa County (Scottsdale/Mesa)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://www.mcso.org/Jailinfo/InmateSearch" },
  "855": { county: "Maricopa County (Mesa/Gilbert)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://www.mcso.org/Jailinfo/InmateSearch" },
  "856": { county: "Maricopa County (Glendale)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://www.mcso.org/Jailinfo/InmateSearch" },
  "857": { county: "Maricopa County (Chandler/Tempe)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://www.mcso.org/Jailinfo/InmateSearch" },
  "858": { county: "Pima County (Tucson)", state: "Arizona", stateCode: "AZ", inmateUrl: "https://corrections.az.gov/public-inmate-search" },
  // Nevada
  "890": { county: "Clark County (Las Vegas)", state: "Nevada", stateCode: "NV", inmateUrl: "https://www.ccdc.net/inmateinfo/inmateinfo.aspx", urlNote: "Clark County Detention Center" },
  "891": { county: "Clark County (Las Vegas)", state: "Nevada", stateCode: "NV", inmateUrl: "https://www.ccdc.net/inmateinfo/inmateinfo.aspx" },
  "893": { county: "Clark County (Henderson)", state: "Nevada", stateCode: "NV", inmateUrl: "https://www.ccdc.net/inmateinfo/inmateinfo.aspx" },
  "895": { county: "Washoe County (Reno)", state: "Nevada", stateCode: "NV", inmateUrl: "https://vinelink.vineapps.com/search/NV/Person" },
  "897": { county: "Washoe County (Reno)", state: "Nevada", stateCode: "NV", inmateUrl: "https://vinelink.vineapps.com/search/NV/Person" },
  // California
  "900": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax", urlNote: "LA County Sheriff Inmate Information Center" },
  "901": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "902": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "903": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "904": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "905": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "906": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "907": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "908": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "910": { county: "Los Angeles County (Pasadena/Burbank)", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "911": { county: "Los Angeles County", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "912": { county: "Los Angeles County (San Gabriel Valley)", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "913": { county: "Los Angeles County (SE)", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "914": { county: "Ventura County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "915": { county: "Los Angeles County (Glendale/Burbank)", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "916": { county: "Los Angeles County (Burbank area)", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "917": { county: "Los Angeles County (Alhambra area)", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "918": { county: "Los Angeles County (Pasadena/Altadena)", state: "California", stateCode: "CA", inmateUrl: "https://app4.lasd.org/iic/ajax" },
  "919": { county: "San Diego County", state: "California", stateCode: "CA", inmateUrl: "https://apps.sdsheriff.net/ois/", urlNote: "San Diego County Sheriff inmate lookup" },
  "920": { county: "San Diego County", state: "California", stateCode: "CA", inmateUrl: "https://apps.sdsheriff.net/ois/" },
  "921": { county: "San Diego County (downtown)", state: "California", stateCode: "CA", inmateUrl: "https://apps.sdsheriff.net/ois/" },
  "922": { county: "San Bernardino County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "923": { county: "Riverside County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "924": { county: "Riverside County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "925": { county: "San Bernardino County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "926": { county: "Orange County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "927": { county: "Orange County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "928": { county: "Riverside County (Indio/Coachella)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "930": { county: "Ventura County (Oxnard)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "931": { county: "Ventura County (Oxnard)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "935": { county: "Fresno County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "936": { county: "Fresno County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "937": { county: "Fresno County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "940": { county: "San Francisco County", state: "California", stateCode: "CA", inmateUrl: "https://sfgov.org/sfsheriff/inmate-lookup", urlNote: "San Francisco Sheriff's Office" },
  "941": { county: "San Francisco County", state: "California", stateCode: "CA", inmateUrl: "https://sfgov.org/sfsheriff/inmate-lookup" },
  "943": { county: "San Mateo County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "945": { county: "Contra Costa County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "946": { county: "Alameda County (Oakland)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "947": { county: "Alameda County (Berkeley/Hayward)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "948": { county: "Marin County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "949": { county: "Sonoma / Marin County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "950": { county: "Santa Clara County (San Jose)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "951": { county: "Santa Clara County (San Jose)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "952": { county: "Santa Clara County (Silicon Valley)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "953": { county: "Santa Clara County (Sunnyvale/Cupertino)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "954": { county: "Sonoma County (Santa Rosa)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "955": { county: "Shasta County (Redding)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "956": { county: "Sacramento County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "957": { county: "Sacramento County", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  "958": { county: "Sacramento County (Placer)", state: "California", stateCode: "CA", inmateUrl: "https://vinelink.vineapps.com/search/CA/Person" },
  // Oregon
  "970": { county: "Multnomah County (Portland)", state: "Oregon", stateCode: "OR", inmateUrl: "https://vinelink.vineapps.com/search/OR/Person" },
  "971": { county: "Multnomah County (Portland)", state: "Oregon", stateCode: "OR", inmateUrl: "https://vinelink.vineapps.com/search/OR/Person" },
  "972": { county: "Clackamas / Washington County", state: "Oregon", stateCode: "OR", inmateUrl: "https://vinelink.vineapps.com/search/OR/Person" },
  "973": { county: "Salem area (Marion County)", state: "Oregon", stateCode: "OR", inmateUrl: "https://vinelink.vineapps.com/search/OR/Person" },
  "974": { county: "Lane County (Eugene)", state: "Oregon", stateCode: "OR", inmateUrl: "https://vinelink.vineapps.com/search/OR/Person" },
  // Washington State
  "980": { county: "King County (Seattle)", state: "Washington", stateCode: "WA", inmateUrl: "https://www.kingcounty.gov/depts/sheriff/jail/inmate-information.aspx", urlNote: "King County Sheriff's Office" },
  "981": { county: "King County (Seattle)", state: "Washington", stateCode: "WA", inmateUrl: "https://www.kingcounty.gov/depts/sheriff/jail/inmate-information.aspx" },
  "982": { county: "Pierce County (Tacoma)", state: "Washington", stateCode: "WA", inmateUrl: "https://vinelink.vineapps.com/search/WA/Person" },
  "983": { county: "Pierce County (Tacoma)", state: "Washington", stateCode: "WA", inmateUrl: "https://vinelink.vineapps.com/search/WA/Person" },
  "984": { county: "Snohomish County (Everett)", state: "Washington", stateCode: "WA", inmateUrl: "https://vinelink.vineapps.com/search/WA/Person" },
  "985": { county: "Snohomish County (Everett)", state: "Washington", stateCode: "WA", inmateUrl: "https://vinelink.vineapps.com/search/WA/Person" },
  "989": { county: "Spokane County", state: "Washington", stateCode: "WA", inmateUrl: "https://vinelink.vineapps.com/search/WA/Person" },
  "990": { county: "Spokane County", state: "Washington", stateCode: "WA", inmateUrl: "https://vinelink.vineapps.com/search/WA/Person" },
  "991": { county: "Spokane County", state: "Washington", stateCode: "WA", inmateUrl: "https://vinelink.vineapps.com/search/WA/Person" },
  "996": { county: "Anchorage Municipality", state: "Alaska", stateCode: "AK", inmateUrl: "https://vinelink.vineapps.com/search/AK/Person" },
  "997": { county: "Anchorage / Fairbanks area", state: "Alaska", stateCode: "AK", inmateUrl: "https://vinelink.vineapps.com/search/AK/Person" },
  "998": { county: "Fairbanks / Interior Alaska", state: "Alaska", stateCode: "AK", inmateUrl: "https://vinelink.vineapps.com/search/AK/Person" },
  "967": { county: "Hawaii County / Oahu", state: "Hawaii", stateCode: "HI", inmateUrl: "https://vinelink.vineapps.com/search/HI/Person" },
  "968": { county: "Honolulu County (Oahu)", state: "Hawaii", stateCode: "HI", inmateUrl: "https://vinelink.vineapps.com/search/HI/Person" },
};

export function lookupZip(zip: string): CountyResult | null {
  const digits = zip.replace(/\D/g, "");
  if (digits.length < 5) return null;
  const zip3 = digits.slice(0, 3);
  return ZIP3_LOOKUP[zip3] ?? null;
}

// Returns true when the inmate URL is a generic statewide tool (VINELink or state DOC)
// rather than a direct county sheriff page.
export function isStatewideUrl(url: string): boolean {
  return url.includes("vinelink") || url.includes(".state.") || url.includes("doccs") || url.includes("tdcj.texas") || url.includes("vadoc.virginia") || url.includes("webapps.doc.state") || url.includes("appgateway.drc") || url.includes("appsdoc.wi") || url.includes("corrections.az") || url.includes("mdocweb");
}

// No auto-inference from first digit — too many states share the same first digit.
// When a ZIP is not found, callers should show the state dropdown for manual selection.
export function getStateFallback(_zip: string): null {
  return null;
}
