// Generated from the attorney-reviewed North Carolina title worksheet.
// This intentionally contains display names only; review notes remain server-side.

export const NORTH_CAROLINA_APPROVED_DISPLAY_NAMES: Record<string, string> = {
  "nc-accessory-after-the-fact": "Accessory After the Fact",
  "nc-aggravated-assault": "Assault with Deadly Weapon, Intend to Kill or Seriously Injure",
  "nc-aiding-and-abetting": "Accessory Before the Fact",
  "nc-alcohol-in-park": "Unlawful Possession and Consumption of Alcohol",
  "nc-animal-at-large": "Unaccompanied Dog at Night",
  "nc-assault-in-the-second-degree": "Asssault on a Disabled Individual",
  "nc-assault-in-the-third-degree": "Simple Assault and/or Battery",
  "nc-auto-burglary": "Breaking and Entering Into Vehicles",
  "nc-check-fraud": "Check Fraud",
  "nc-child-sexual-abuse": "Child Sexual Abuse",
  "nc-contempt-of-court": "Criminal Contempt ",
  "nc-credit-card-fraud": "Credit Card Theft/Fraud",
  "nc-discharge-of-firearm-in-city": "Discharge Firearm into Occupied Property",
  "nc-disturbing-the-peace": "Disorderly conduct",
  "nc-domestic-violence-protective-order-violation": "Protective Order Violation ",
  "nc-driving-while-license-revoked": "Driving While License Revoked",
  "nc-dui-first-offense": "Impaired Driving",
  "nc-embezzlement": "Embezzlement via Office or Employment",
  "nc-expired-registration": "Driving Without Registration",
  "nc-failure-to-pay-child-support": "Failure to Support Spouse and Children",
  "nc-false-info-to-police": "False Reports to Law Enforcement",
  "nc-felon-in-possession-of-firearm": "Possession of Firearms by Felon",
  "nc-forgery": "Forgery or Counterfeiting",
  "nc-gang-enhancement": "Criminal Street Gang Enhancement",
  "nc-hate-crime-enhancement": "Hate Crime Enhancement",
  "nc-hit-and-run": "Duty to Stop - Hit and Run",
  "nc-illegal-fireworks": "Illegal Discharge of Fireworks",
  "nc-indecent-exposure": "Indecent exposure",
  "nc-injury-to-personal-property": "Willful and Wonton Injury to Personal Property",
  "nc-insurance-fraud": "Insurance Fraud",
  "nc-juvenile-firearm-possession": "Posession of Weapons on Educational Property",
  "nc-littering": "Littering",
  "nc-loitering": "Disorderly Conduct - Vandalism of Public Property",
  "nc-mail-fraud": "Obtaining property by false pretenses",
  "nc-menacing": "Communicating threats",
  "nc-minor-in-possession": "Sell to or Purchase by Minors",
  "nc-murder-in-the-second-degree": "Murder in the Second Degree",
  "nc-protective-order-violation": "Violation of Protective Order",
  "nc-public-intoxication": "Intoxicated and Distruptive in Public",
  "nc-rape-in-the-first-degree": "Rape (Forcible) - First Degree",
  "nc-rape-in-the-second-degree": "Rape (Forcible) - Second Degree",
  "nc-residential-burglary": "Burglary in the Second Degree",
  "nc-rico-organized-crime": "Rackateering",
  "nc-robbery-in-the-first-degree": "Armed Robbery",
  "nc-sexual-assault-in-the-second-degree": "Sexual Offense (Forcible) - First Degree",
  "nc-sexual-assault-in-the-third-degree": "Sexual Offense (Forcible) - Second Degree",
  "nc-sexual-exploitation-of-minor": "Sexual Exploitation of Minor - First Degree",
  "nc-shoplifting": "Shoplifting (Concealment of Merchandise)",
  "nc-solicitation": "Prostitution",
  "nc-statutory-rape": "Statutory Sexual Offense",
  "nc-theft-by-receiving": "Receiving or Possessing Stolen Goods",
  "nc-trespass-after-warning": "Domestic Criminal Trespass",
  "nc-trespassing": "Trespass - First Degree",
  "nc-unlawful-carrying-of-weapon": "Carrying Concealed Weapon",
  "nc-vandalism": "Willful and Wonton Injury to Real Property",
  "nc-wire-fraud": "Obtaining property by false pretenses"
};

export function getNorthCarolinaApprovedDisplayName(
  chargeId: string,
): string | undefined {
  return NORTH_CAROLINA_APPROVED_DISPLAY_NAMES[chargeId];
}
