import type { CriminalCharge } from "./criminal-charges";
import type { ChargeExplanation } from "./charge-explanations";

const records = [
  {
    section: "2903.31", slug: "hazing", name: "Hazing", nameEs: "Novatadas", category: "misdemeanor" as const,
    summary: "Ohio § 2903.31 defines hazing as an act of initiation into an organization, an act to continue or reinstate membership in or affiliation with an organization, or coercing another to perform such an act, that causes or creates a substantial risk of mental or physical harm. It is not limited to students or initial initiation. Organization includes affiliated national or international fraternity/sorority organizations. Division (B) prohibits reckless participation and separately prohibits administrators, employees, faculty members, teachers, consultants, alumni and volunteers from recklessly permitting hazing of someone associated with their organization, including public or private educational institutions. Division (C) requires hazing that includes coerced consumption of alcohol or a statutory drug of abuse resulting in serious physical harm. Serious injury alone does not establish that coerced-consumption branch. Drug of abuse includes controlled substances, harmful intoxicants and dangerous drugs under the incorporated definitions; classification of a particular substance requires separate review.",
    es: "La sección 2903.31 de Ohio define las novatadas como un acto de ingreso a una organización, un acto para continuar o restablecer la condición de miembro o la afiliación a ella, o coaccionar a otra persona para realizar tal acto, que cause o cree un riesgo sustancial de daño mental o físico. No se limita a estudiantes ni al ingreso inicial. Organización incluye entidades nacionales o internacionales afiliadas a fraternidades o sororidades. El apartado (B) prohíbe participar con imprudencia temeraria y, por separado, que administradores, empleados, docentes, profesores, consultores, exalumnos y voluntarios permitan con esa imprudencia novatadas contra alguien vinculado a su organización, incluidas instituciones educativas públicas o privadas. El apartado (C) exige novatadas que incluyan consumo coaccionado de alcohol o una droga de abuso definida por ley, que resulte en daño físico grave. Una lesión grave por sí sola no establece esa variante de consumo coaccionado. Droga de abuso incluye sustancias controladas, intoxicantes nocivos y medicamentos peligrosos según las definiciones incorporadas; clasificar una sustancia concreta requiere revisión separada.",
    penalty: "Division (B)(1) or (2) is a second-degree misdemeanor: up to 90 days in jail and a fine up to $750. Division (C)(1) or (2), with coerced alcohol/drug consumption resulting in serious physical harm, is a third-degree felony. Ordinary F3 prison terms, if imposed, are 9, 12, 18, 24, 30 or 36 months, with a fine up to $10,000. These are conditional base limits, not fixed fines, guaranteed sentences or universal total maximums; other allegations and sanctions require separate review.",
    sources: ["2903.31", "2901.22", "2901.01", "3719.011", "2929.24", "2929.28", "2929.14", "2929.18"],
  },
  {
    section: "2903.311", slug: "reckless-failure-to-immediately-report-knowledge-of-hazing",
    name: "Reckless failure to immediately report knowledge of hazing",
    nameEs: "Omisión temeraria de denunciar inmediatamente el conocimiento de novatadas", category: "misdemeanor" as const,
    summary: "Ohio § 2903.311 applies to an organization's administrator, employee, faculty member, teacher, consultant, alumnus or volunteer who is acting in an official and professional capacity. It prohibits recklessly failing to immediately report knowledge of hazing to a law enforcement agency in the county where the victim resides or where the hazing is occurring or occurred. A report only to school or organization officials does not satisfy the stated law-enforcement destination. This is not a general duty imposed on every bystander. Hazing and organization use § 2903.31's definitions, including continuing or reinstating membership or affiliation and affiliated national/international organizations. Unlike § 2903.31's felony branch, this section's serious-physical-harm enhancement does not require coerced alcohol or drug consumption.",
    es: "La sección 2903.311 de Ohio se aplica al administrador, empleado, docente, profesor, consultor, exalumno o voluntario de una organización que actúe en una capacidad oficial y profesional. Prohíbe omitir con imprudencia temeraria la denuncia inmediata del conocimiento de novatadas ante un organismo policial del condado donde reside la víctima o donde ocurren u ocurrieron las novatadas. Informar solo a autoridades escolares o de la organización no cumple el destino policial indicado. No es un deber general impuesto a todo testigo. Novatadas y organización tienen las definiciones de la sección 2903.31, incluida la continuación o el restablecimiento de la condición de miembro o la afiliación y las entidades nacionales o internacionales afiliadas. A diferencia de la variante de delito grave de la sección 2903.31, el aumento por daño físico grave de esta sección no exige consumo coaccionado de alcohol o drogas.",
    penalty: "Ordinarily a fourth-degree misdemeanor: up to 30 days in jail and a fine up to $250. If the hazing causes serious physical harm, it is a first-degree misdemeanor: up to 180 days in jail and a fine up to $1,000. The enhancement remains a misdemeanor, not a felony. These are conditional base ceilings, not fixed fines or guaranteed sentences; other allegations and sanctions require separate review.",
    sources: ["2903.311", "2903.31", "3719.011", "2901.22", "2901.01", "2929.24", "2929.28"],
  },
  {
    section: "2903.32", slug: "female-genital-mutilation", name: "Female genital mutilation",
    nameEs: "Mutilación genital femenina", category: "felony" as const,
    summary: "Ohio § 2903.32 prohibits knowingly circumcising, excising or infibulating any part of the labia majora, labia minora or clitoris of another person under eighteen. It separately prohibits knowingly transporting a minor to a facility or location for the purpose of facilitating that prohibited act. The section does not apply to a procedure performed for medical purposes by a physician or licensed health care professional when the act is within the scope of that person's license; a license alone does not establish the exception. Physician and licensed health care professional have the section's specific authorization definitions. Cultural or ritual necessity, the minor's consent, and the parent or guardian's consent are not defenses under this section. This is not a determination of an individual professional's license or its scope.",
    es: "La sección 2903.32 de Ohio prohíbe circuncidar, extirpar o infibular a sabiendas cualquier parte de los labios mayores, labios menores o clítoris de otra persona menor de dieciocho años. También prohíbe transportar a sabiendas a un menor a un establecimiento o lugar con el propósito de facilitar ese acto prohibido. La sección no se aplica a un procedimiento con fines médicos realizado por un médico u otro profesional sanitario autorizado cuando el acto esté dentro del ámbito de su licencia; tener licencia por sí solo no establece la excepción. Médico y profesional sanitario autorizado tienen las definiciones específicas de autorización de esta sección. La necesidad cultural o ritual, el consentimiento del menor y el consentimiento de su padre, madre o tutor no son defensas según esta sección. Esto no determina la licencia ni el ámbito profesional de una persona concreta.",
    penalty: "A second-degree felony. For conduct on or after March 22, 2019, ordinary minimum prison terms, if imposed, are 2–8 years, with an indefinite maximum under § 2929.144; for one qualifying felony, maximum equals minimum plus 50%. The ordinary F2 fine ceiling is $15,000. In addition, § 2903.32(B) requires the court to impose an additional fine of up to $25,000: imposing an additional fine is mandatory, but $25,000 is a ceiling, not a fixed amount. The two described fine ceilings can total $40,000; that is not a universal cap on all sanctions or costs. The section became effective April 5, 2019; the general sentencing date is not certification that this offense existed earlier. Other allegations and aggregate sentences require separate review.",
    sources: ["2903.32", "2901.22", "2929.14", "2929.18", "2929.144"],
  },
];

export const OHIO_HAZING_AND_PROTECTION_CHARGES: CriminalCharge[] = records.map(row => ({
  id: `oh-orc-${row.section.replace(".", "-")}-${row.slug}`,
  name: row.name, nameEs: row.nameEs, jurisdiction: "OH", category: row.category, code: row.section,
  description: row.summary, descriptionEs: row.es, maxPenalty: row.penalty,
  commonDefenses: [], evidenceToGather: [], specificRights: [], urgentActions: [],
  statuteCitations: [`Ohio Rev. Code Ann. § ${row.section}`],
  sourceUrls: [`https://codes.ohio.gov/ohio-revised-code/section-${row.section}`],
  dataConfidence: "high", lastVerified: "2026-09",
}));
export const OHIO_HAZING_AND_PROTECTION_EXPLANATIONS: ChargeExplanation[] = records.map(row => ({
  jurisdiction: "OH", slug: `ohio-${row.slug}`, chargePattern: new RegExp(`^${row.name}$`, "i"),
  plainSummary: row.summary, degreeContext: row.penalty, keyTerms: [], pendingAttorneyReview: true,
  sources: row.sources.map(section => ({
    jurisdiction: "OH", citation: `Ohio Rev. Code § ${section}`, url: `https://codes.ohio.gov/ohio-revised-code/section-${section}`,
  })),
}));