/**
 * State Citation Generator: CA, TX, IL
 *
 * Generates verified citations for CA, TX, and IL charges using curated mappings
 * researched against official state legislature sources. Entries are added at
 * confidence "medium" — run promote-verified-citations.ts after spot-checking to
 * promote confirmed entries to "high".
 *
 * Sources:
 *   CA — leginfo.legislature.ca.gov (California Official Statutes)
 *   TX — statutes.capitol.texas.gov (Texas Legislature Online)
 *   IL — ilga.gov / law.justia.com/codes/illinois (Illinois General Assembly)
 *
 * Usage:
 *   npx tsx scripts/data-review/generate-state-citations.ts [options]
 *
 *   --state CA|TX|IL   Process only one state (default: all three)
 *   --apply            Write entries into shared/criminal-charge-citations.ts
 *   --dry-run          Print what would be written without touching any file
 */

import fs from 'fs';
import path from 'path';

// ── CLI args ──────────────────────────────────────────────────────────────────
const DRY_RUN    = process.argv.includes('--dry-run');
const APPLY      = process.argv.includes('--apply');
const stateArgI  = process.argv.indexOf('--state');
const STATE_FILTER: string | null = stateArgI !== -1
  ? (process.argv[stateArgI + 1] ?? '').toUpperCase()
  : null;

const VERIFIED_MONTH = new Date().toISOString().slice(0, 7);

// ── Citation record ───────────────────────────────────────────────────────────

interface CitationEntry {
  chargeId: string;
  citation: string;
  confidence: 'medium';
  source: string;
  sourceUrl: string;
  skip?: boolean; // local ordinance or federal-only; exclude from overlay
}

// ── Helper: leginfo URL (official CA legislature) ─────────────────────────────
// lawCode: PEN | VEH | HSC | WIC | BPC | FGC | EDC | RTC
// section: section number, e.g. "187" or "23152"
function caLeginfo(lawCode: string, section: string): string {
  const s = section.replace(/[()]/g, ''); // strip parens for URL
  return `https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=${lawCode}&sectionNum=${s}.`;
}

// Texas Legislature chapter-level URL
function txUrl(codePrefix: string, chapter: string): string {
  return `https://statutes.capitol.texas.gov/Docs/${codePrefix}/htm/${codePrefix}.${chapter}.htm`;
}

// Illinois Justia URL (720 ILCS 5 = Criminal Code; 625 ILCS 5 = Vehicle)
function ilJustia(chapter: string, act: string, section: string): string {
  return `https://law.justia.com/codes/illinois/chapter-${chapter}/act-${act}/section-${act}-${section}/`;
}

// ILGA official URL
function ilga(actId: string, section: string): string {
  return `https://www.ilga.gov/legislation/ilcs/fulltext.asp?Name=${actId}`;
}

// ── CA MAPPING ────────────────────────────────────────────────────────────────
// Source: California Official Statutes (leginfo.legislature.ca.gov)
// PC = Cal. Penal Code, VC = Cal. Vehicle Code,
// HSC = Cal. Health & Safety Code, WIC = Cal. Welf. & Inst. Code,
// BPC = Cal. Bus. & Prof. Code, FGC = Cal. Fish & Game Code,
// EC = Cal. Educ. Code, RTC = Cal. Rev. & Tax. Code

const CA_CITATIONS: CitationEntry[] = [
  // ── Homicide ──
  { chargeId: 'ca-murder-in-the-first-degree',
    citation: 'Cal. Penal Code §§ 187(a), 189(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 187, 189',
    sourceUrl: caLeginfo('PEN', '189') },
  { chargeId: 'ca-murder-in-the-second-degree',
    citation: 'Cal. Penal Code § 187(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 187',
    sourceUrl: caLeginfo('PEN', '187') },
  { chargeId: 'ca-voluntary-manslaughter',
    citation: 'Cal. Penal Code § 192(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 192(a)',
    sourceUrl: caLeginfo('PEN', '192') },
  { chargeId: 'ca-involuntary-manslaughter',
    citation: 'Cal. Penal Code § 192(b)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 192(b)',
    sourceUrl: caLeginfo('PEN', '192') },
  { chargeId: 'ca-criminally-negligent-homicide',
    citation: 'Cal. Penal Code § 192(c)(2)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 192(c)(2)',
    sourceUrl: caLeginfo('PEN', '192') },
  { chargeId: 'ca-vehicular-homicide',
    citation: 'Cal. Penal Code § 191.5(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 191.5',
    sourceUrl: caLeginfo('PEN', '191.5') },
  { chargeId: 'ca-felony-murder',
    citation: 'Cal. Penal Code § 189(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 189(a)',
    sourceUrl: caLeginfo('PEN', '189') },
  // ── Assault / Battery ──
  { chargeId: 'ca-assault-in-the-second-degree',
    citation: 'Cal. Penal Code § 243(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 243 (Battery)',
    sourceUrl: caLeginfo('PEN', '243') },
  { chargeId: 'ca-assault-in-the-third-degree',
    citation: 'Cal. Penal Code § 240',
    confidence: 'medium', source: 'California Legislature — Penal Code § 240 (Assault)',
    sourceUrl: caLeginfo('PEN', '240') },
  { chargeId: 'ca-assault-with-deadly-weapon',
    citation: 'Cal. Penal Code § 245(a)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 245(a)(1)',
    sourceUrl: caLeginfo('PEN', '245') },
  { chargeId: 'ca-domestic-violence-assault',
    citation: 'Cal. Penal Code § 243(e)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 243(e)(1)',
    sourceUrl: caLeginfo('PEN', '243') },
  { chargeId: 'ca-assault-on-peace-officer',
    citation: 'Cal. Penal Code § 241(b)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 241(b)',
    sourceUrl: caLeginfo('PEN', '241') },
  { chargeId: 'ca-menacing',
    citation: 'Cal. Penal Code § 422',
    confidence: 'medium', source: 'California Legislature — Penal Code § 422 (Criminal Threats)',
    sourceUrl: caLeginfo('PEN', '422') },
  { chargeId: 'ca-domestic-battery',
    citation: 'Cal. Penal Code § 243(e)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 243(e)(1)',
    sourceUrl: caLeginfo('PEN', '243') },
  // ── Sex offenses ──
  { chargeId: 'ca-rape-in-the-first-degree',
    citation: 'Cal. Penal Code § 261(a)(2)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 261',
    sourceUrl: caLeginfo('PEN', '261') },
  { chargeId: 'ca-sexual-assault-in-the-second-degree',
    citation: 'Cal. Penal Code § 289(a)(1)(A)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 289',
    sourceUrl: caLeginfo('PEN', '289') },
  { chargeId: 'ca-sexual-assault-in-the-third-degree',
    citation: 'Cal. Penal Code § 243.4(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 243.4 (Sexual Battery)',
    sourceUrl: caLeginfo('PEN', '243.4') },
  { chargeId: 'ca-statutory-rape',
    citation: 'Cal. Penal Code § 261.5(c)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 261.5',
    sourceUrl: caLeginfo('PEN', '261.5') },
  { chargeId: 'ca-child-sexual-abuse',
    citation: 'Cal. Penal Code § 288(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 288',
    sourceUrl: caLeginfo('PEN', '288') },
  { chargeId: 'ca-sexual-exploitation-of-minor',
    citation: 'Cal. Penal Code § 311.4(b)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 311.4',
    sourceUrl: caLeginfo('PEN', '311.4') },
  // ── Theft / Property ──
  { chargeId: 'ca-grand-theft-in-the-first-degree',
    citation: 'Cal. Penal Code § 487(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 487 (Grand Theft)',
    sourceUrl: caLeginfo('PEN', '487') },
  { chargeId: 'ca-petty-theft',
    citation: 'Cal. Penal Code § 484(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 484',
    sourceUrl: caLeginfo('PEN', '484') },
  { chargeId: 'ca-petty-theft-misdemeanor',
    citation: 'Cal. Penal Code §§ 484(a), 488',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 484, 488',
    sourceUrl: caLeginfo('PEN', '488') },
  { chargeId: 'ca-theft-by-receiving',
    citation: 'Cal. Penal Code § 496(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 496',
    sourceUrl: caLeginfo('PEN', '496') },
  { chargeId: 'ca-identity-theft',
    citation: 'Cal. Penal Code § 530.5(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 530.5',
    sourceUrl: caLeginfo('PEN', '530.5') },
  { chargeId: 'ca-credit-card-fraud',
    citation: 'Cal. Penal Code § 484e(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 484e',
    sourceUrl: caLeginfo('PEN', '484e') },
  { chargeId: 'ca-embezzlement',
    citation: 'Cal. Penal Code § 503',
    confidence: 'medium', source: 'California Legislature — Penal Code § 503',
    sourceUrl: caLeginfo('PEN', '503') },
  { chargeId: 'ca-shoplifting',
    citation: 'Cal. Penal Code § 459.5(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 459.5 (Prop 47)',
    sourceUrl: caLeginfo('PEN', '459.5') },
  { chargeId: 'ca-check-fraud',
    citation: 'Cal. Penal Code § 476',
    confidence: 'medium', source: 'California Legislature — Penal Code § 476',
    sourceUrl: caLeginfo('PEN', '476') },
  { chargeId: 'ca-bad-checks',
    citation: 'Cal. Penal Code § 476a',
    confidence: 'medium', source: 'California Legislature — Penal Code § 476a',
    sourceUrl: caLeginfo('PEN', '476a') },
  { chargeId: 'ca-forgery',
    citation: 'Cal. Penal Code § 470(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 470',
    sourceUrl: caLeginfo('PEN', '470') },
  { chargeId: 'ca-fake-id',
    citation: 'Cal. Penal Code § 470b',
    confidence: 'medium', source: 'California Legislature — Penal Code § 470b',
    sourceUrl: caLeginfo('PEN', '470b') },
  { chargeId: 'ca-computer-fraud',
    citation: 'Cal. Penal Code § 502(c)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 502',
    sourceUrl: caLeginfo('PEN', '502') },
  // Federal-only equivalents — use PC § 532 as closest CA state analog
  { chargeId: 'ca-wire-fraud',
    citation: 'Cal. Penal Code § 532(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 532 (Obtaining property by false pretenses; federal wire fraud = 18 U.S.C. § 1343)',
    sourceUrl: caLeginfo('PEN', '532') },
  { chargeId: 'ca-mail-fraud',
    citation: 'Cal. Penal Code § 532(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 532 (state analog; federal mail fraud = 18 U.S.C. § 1341)',
    sourceUrl: caLeginfo('PEN', '532') },
  { chargeId: 'ca-insurance-fraud',
    citation: 'Cal. Penal Code § 550(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 550',
    sourceUrl: caLeginfo('PEN', '550') },
  { chargeId: 'ca-tax-fraud',
    citation: 'Cal. Rev. & Tax. Code § 19706',
    confidence: 'medium', source: 'California Legislature — Revenue and Taxation Code § 19706',
    sourceUrl: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=RTC&sectionNum=19706.' },
  // ── Burglary / Robbery ──
  { chargeId: 'ca-burglary-in-the-first-degree',
    citation: 'Cal. Penal Code §§ 459, 460(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 459, 460(a) (inhabited dwelling = 1st degree)',
    sourceUrl: caLeginfo('PEN', '460') },
  { chargeId: 'ca-burglary-in-the-second-degree',
    citation: 'Cal. Penal Code §§ 459, 460(b)',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 459, 460(b) (commercial = 2nd degree)',
    sourceUrl: caLeginfo('PEN', '460') },
  { chargeId: 'ca-robbery-in-the-first-degree',
    citation: 'Cal. Penal Code §§ 211, 212.5(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 211, 212.5(a) (robbery 1st degree)',
    sourceUrl: caLeginfo('PEN', '212.5') },
  { chargeId: 'ca-robbery-in-the-second-degree',
    citation: 'Cal. Penal Code §§ 211, 212.5(c)',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 211, 212.5(c) (robbery 2nd degree)',
    sourceUrl: caLeginfo('PEN', '212.5') },
  { chargeId: 'ca-carjacking',
    citation: 'Cal. Penal Code § 215(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 215',
    sourceUrl: caLeginfo('PEN', '215') },
  { chargeId: 'ca-bank-robbery',
    citation: 'Cal. Penal Code § 211',
    confidence: 'medium', source: 'California Legislature — Penal Code § 211 (bank robbery prosecuted as robbery in CA; federal = 18 U.S.C. § 2113)',
    sourceUrl: caLeginfo('PEN', '211') },
  // ── Drugs ──
  { chargeId: 'ca-possession-of-controlled-substance',
    citation: 'Cal. Health & Safety Code § 11350(a)',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 11350',
    sourceUrl: caLeginfo('HSC', '11350') },
  { chargeId: 'ca-possession-with-intent-to-distribute',
    citation: 'Cal. Health & Safety Code § 11351',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 11351',
    sourceUrl: caLeginfo('HSC', '11351') },
  { chargeId: 'ca-distribution-of-controlled-substance',
    citation: 'Cal. Health & Safety Code § 11352(a)',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 11352',
    sourceUrl: caLeginfo('HSC', '11352') },
  { chargeId: 'ca-manufacturing-controlled-substance',
    citation: 'Cal. Health & Safety Code § 11379.6(a)',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 11379.6',
    sourceUrl: caLeginfo('HSC', '11379.6') },
  { chargeId: 'ca-drug-trafficking',
    citation: 'Cal. Health & Safety Code § 11352(a)',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 11352 (transportation/sale)',
    sourceUrl: caLeginfo('HSC', '11352') },
  { chargeId: 'ca-possession-of-drug-paraphernalia',
    citation: 'Cal. Health & Safety Code § 11364(a)',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 11364',
    sourceUrl: caLeginfo('HSC', '11364') },
  { chargeId: 'ca-maintaining-drug-house',
    citation: 'Cal. Health & Safety Code § 11366',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 11366',
    sourceUrl: caLeginfo('HSC', '11366') },
  // ── Weapons ──
  { chargeId: 'ca-unlawful-carrying-of-weapon',
    citation: 'Cal. Penal Code § 25400(a)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 25400 (carrying concealed firearm)',
    sourceUrl: caLeginfo('PEN', '25400') },
  { chargeId: 'ca-felon-in-possession-of-firearm',
    citation: 'Cal. Penal Code § 29800(a)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 29800',
    sourceUrl: caLeginfo('PEN', '29800') },
  { chargeId: 'ca-discharge-of-firearm-in-city',
    citation: 'Cal. Penal Code § 246.3(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 246.3',
    sourceUrl: caLeginfo('PEN', '246.3') },
  { chargeId: 'ca-possession-of-prohibited-weapon',
    citation: 'Cal. Penal Code § 16590',
    confidence: 'medium', source: 'California Legislature — Penal Code § 16590 (generally prohibited weapons; specific offense section varies by weapon type)',
    sourceUrl: caLeginfo('PEN', '16590') },
  // ── Public order ──
  { chargeId: 'ca-disorderly-conduct',
    citation: 'Cal. Penal Code § 647',
    confidence: 'medium', source: 'California Legislature — Penal Code § 647',
    sourceUrl: caLeginfo('PEN', '647') },
  { chargeId: 'ca-public-intoxication',
    citation: 'Cal. Penal Code § 647(f)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 647(f)',
    sourceUrl: caLeginfo('PEN', '647') },
  { chargeId: 'ca-disturbing-the-peace',
    citation: 'Cal. Penal Code § 415',
    confidence: 'medium', source: 'California Legislature — Penal Code § 415',
    sourceUrl: caLeginfo('PEN', '415') },
  { chargeId: 'ca-noise-violation',
    citation: 'Cal. Penal Code § 415',
    confidence: 'medium', source: 'California Legislature — Penal Code § 415',
    sourceUrl: caLeginfo('PEN', '415') },
  { chargeId: 'ca-trespassing',
    citation: 'Cal. Penal Code § 602(m)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 602',
    sourceUrl: caLeginfo('PEN', '602') },
  { chargeId: 'ca-trespass-after-warning',
    citation: 'Cal. Penal Code § 602(o)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 602(o) (return after being asked to leave)',
    sourceUrl: caLeginfo('PEN', '602') },
  { chargeId: 'ca-vandalism',
    citation: 'Cal. Penal Code § 594(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 594',
    sourceUrl: caLeginfo('PEN', '594') },
  { chargeId: 'ca-loitering',
    citation: 'Cal. Penal Code § 647(b)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 647(b)',
    sourceUrl: caLeginfo('PEN', '647') },
  { chargeId: 'ca-indecent-exposure',
    citation: 'Cal. Penal Code § 314(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 314',
    sourceUrl: caLeginfo('PEN', '314') },
  { chargeId: 'ca-panhandling',
    citation: 'Cal. Penal Code § 647(c)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 647(c)',
    sourceUrl: caLeginfo('PEN', '647') },
  { chargeId: 'ca-illegal-camping',
    citation: 'Cal. Penal Code § 647(e)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 647(e)',
    sourceUrl: caLeginfo('PEN', '647') },
  { chargeId: 'ca-fare-evasion',
    citation: 'Cal. Penal Code § 640(c)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 640 (transit fare evasion)',
    sourceUrl: caLeginfo('PEN', '640') },
  { chargeId: 'ca-prostitution-solicitation',
    citation: 'Cal. Penal Code § 647(b)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 647(b)',
    sourceUrl: caLeginfo('PEN', '647') },
  { chargeId: 'ca-harassment',
    citation: 'Cal. Penal Code § 646.9(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 646.9 (Stalking)',
    sourceUrl: caLeginfo('PEN', '646.9') },
  { chargeId: 'ca-animal-cruelty-misdemeanor',
    citation: 'Cal. Penal Code § 597(b)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 597',
    sourceUrl: caLeginfo('PEN', '597') },
  { chargeId: 'ca-animal-at-large',
    citation: 'Cal. Penal Code § 597t',
    confidence: 'medium', source: 'California Legislature — Penal Code § 597t (local ordinance may also apply)',
    sourceUrl: caLeginfo('PEN', '597t') },
  { chargeId: 'ca-littering',
    citation: 'Cal. Penal Code § 374.4',
    confidence: 'medium', source: 'California Legislature — Penal Code § 374.4',
    sourceUrl: caLeginfo('PEN', '374.4') },
  { chargeId: 'ca-illegal-fireworks',
    citation: 'Cal. Health & Safety Code § 12677',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 12677 (dangerous fireworks)',
    sourceUrl: caLeginfo('HSC', '12677') },
  // ── Traffic / Vehicle ──
  { chargeId: 'ca-dui-first-offense',
    citation: 'Cal. Vehicle Code § 23152(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 23152',
    sourceUrl: caLeginfo('VEH', '23152') },
  { chargeId: 'ca-dui-second-offense',
    citation: 'Cal. Vehicle Code §§ 23152(a), 23540',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 23540 (DUI with prior)',
    sourceUrl: caLeginfo('VEH', '23540') },
  { chargeId: 'ca-dui-third-offense',
    citation: 'Cal. Vehicle Code §§ 23152(a), 23546',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 23546 (DUI with 2 priors)',
    sourceUrl: caLeginfo('VEH', '23546') },
  { chargeId: 'ca-reckless-driving',
    citation: 'Cal. Vehicle Code § 23103(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 23103',
    sourceUrl: caLeginfo('VEH', '23103') },
  { chargeId: 'ca-hit-and-run',
    citation: 'Cal. Vehicle Code § 20002(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 20002',
    sourceUrl: caLeginfo('VEH', '20002') },
  { chargeId: 'ca-driving-while-suspended',
    citation: 'Cal. Vehicle Code § 14601.1(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 14601.1',
    sourceUrl: caLeginfo('VEH', '14601.1') },
  { chargeId: 'ca-driving-without-license',
    citation: 'Cal. Vehicle Code § 12500(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 12500',
    sourceUrl: caLeginfo('VEH', '12500') },
  { chargeId: 'ca-driving-without-insurance',
    citation: 'Cal. Vehicle Code § 16029(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 16029',
    sourceUrl: caLeginfo('VEH', '16029') },
  { chargeId: 'ca-expired-registration',
    citation: 'Cal. Vehicle Code § 4000(a)(1)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 4000',
    sourceUrl: caLeginfo('VEH', '4000') },
  { chargeId: 'ca-expired-inspection',
    citation: 'Cal. Vehicle Code § 24002(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 24002',
    sourceUrl: caLeginfo('VEH', '24002') },
  { chargeId: 'ca-open-container',
    citation: 'Cal. Vehicle Code § 23222(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 23222',
    sourceUrl: caLeginfo('VEH', '23222') },
  { chargeId: 'ca-defective-vehicle-equipment',
    citation: 'Cal. Vehicle Code § 24252(a)',
    confidence: 'medium', source: 'California Legislature — Vehicle Code § 24252',
    sourceUrl: caLeginfo('VEH', '24252') },
  // ── Miscellaneous offenses ──
  { chargeId: 'ca-contempt-of-court',
    citation: 'Cal. Penal Code § 166(a)(4)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 166',
    sourceUrl: caLeginfo('PEN', '166') },
  { chargeId: 'ca-protective-order-violation',
    citation: 'Cal. Penal Code § 166(c)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 166(c)',
    sourceUrl: caLeginfo('PEN', '166') },
  { chargeId: 'ca-failure-to-appear',
    citation: 'Cal. Penal Code § 1320(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 1320',
    sourceUrl: caLeginfo('PEN', '1320') },
  { chargeId: 'ca-probation-violation',
    citation: 'Cal. Penal Code § 1203.2(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 1203.2',
    sourceUrl: caLeginfo('PEN', '1203.2') },
  { chargeId: 'ca-resisting-arrest',
    citation: 'Cal. Penal Code § 148(a)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 148',
    sourceUrl: caLeginfo('PEN', '148') },
  { chargeId: 'ca-false-info-to-police',
    citation: 'Cal. Penal Code § 148.9(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 148.9',
    sourceUrl: caLeginfo('PEN', '148.9') },
  { chargeId: 'ca-failure-to-pay-child-support',
    citation: 'Cal. Penal Code § 270',
    confidence: 'medium', source: 'California Legislature — Penal Code § 270',
    sourceUrl: caLeginfo('PEN', '270') },
  { chargeId: 'ca-minor-in-possession',
    citation: 'Cal. Bus. & Prof. Code § 25662(a)',
    confidence: 'medium', source: 'California Legislature — Business & Professions Code § 25662',
    sourceUrl: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=25662.' },
  { chargeId: 'ca-alcohol-in-park',
    citation: 'Cal. Bus. & Prof. Code § 25620',
    confidence: 'medium', source: 'California Legislature — Business & Professions Code § 25620',
    sourceUrl: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=25620.' },
  { chargeId: 'ca-curfew-violation',
    citation: 'Cal. Welf. & Inst. Code § 625.3',
    confidence: 'medium', source: 'California Legislature — Welfare & Institutions Code § 625.3 (juvenile curfew enforcement)',
    sourceUrl: caLeginfo('WIC', '625.3') },
  { chargeId: 'ca-truancy',
    citation: 'Cal. Educ. Code § 48260',
    confidence: 'medium', source: 'California Legislature — Education Code § 48260',
    sourceUrl: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=EDC&sectionNum=48260.' },
  { chargeId: 'ca-hunting-fishing-no-license',
    citation: 'Cal. Fish & Game Code § 7145',
    confidence: 'medium', source: 'California Legislature — Fish & Game Code § 7145',
    sourceUrl: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=FGC&sectionNum=7145.' },
  // ── Attempt / conspiracy / complicity ──
  { chargeId: 'ca-criminal-attempt',
    citation: 'Cal. Penal Code § 664',
    confidence: 'medium', source: 'California Legislature — Penal Code § 664 (Criminal Attempt)',
    sourceUrl: caLeginfo('PEN', '664') },
  { chargeId: 'ca-conspiracy',
    citation: 'Cal. Penal Code § 182(a)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 182',
    sourceUrl: caLeginfo('PEN', '182') },
  { chargeId: 'ca-aiding-and-abetting',
    citation: 'Cal. Penal Code § 31',
    confidence: 'medium', source: 'California Legislature — Penal Code § 31 (Aiding & Abetting)',
    sourceUrl: caLeginfo('PEN', '31') },
  { chargeId: 'ca-accessory-after-the-fact',
    citation: 'Cal. Penal Code § 32',
    confidence: 'medium', source: 'California Legislature — Penal Code § 32',
    sourceUrl: caLeginfo('PEN', '32') },
  { chargeId: 'ca-criminal-solicitation',
    citation: 'Cal. Penal Code § 653f',
    confidence: 'medium', source: 'California Legislature — Penal Code § 653f',
    sourceUrl: caLeginfo('PEN', '653f') },
  { chargeId: 'ca-attempted-murder',
    citation: 'Cal. Penal Code §§ 664, 187(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 664, 187',
    sourceUrl: caLeginfo('PEN', '664') },
  { chargeId: 'ca-attempted-robbery',
    citation: 'Cal. Penal Code §§ 664, 211',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 664, 211',
    sourceUrl: caLeginfo('PEN', '664') },
  { chargeId: 'ca-attempted-sexual-assault',
    citation: 'Cal. Penal Code §§ 664, 261(a)(2)',
    confidence: 'medium', source: 'California Legislature — Penal Code §§ 664, 261',
    sourceUrl: caLeginfo('PEN', '664') },
  // ── Enhancements ──
  { chargeId: 'ca-gang-enhancement',
    citation: 'Cal. Penal Code § 186.22(b)(1)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 186.22 (Street Gang Enhancement)',
    sourceUrl: caLeginfo('PEN', '186.22') },
  { chargeId: 'ca-hate-crime-enhancement',
    citation: 'Cal. Penal Code § 422.75(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 422.75 (Hate Crime Enhancement)',
    sourceUrl: caLeginfo('PEN', '422.75') },
  { chargeId: 'ca-recidivist-enhancement',
    citation: 'Cal. Penal Code §§ 667(b)–(j), 1170.12',
    confidence: 'medium', source: 'California Legislature — Penal Code § 667 (Three Strikes Law)',
    sourceUrl: caLeginfo('PEN', '667') },
  { chargeId: 'ca-firearm-in-felony-enhancement',
    citation: 'Cal. Penal Code § 12022.5(a)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 12022.5 (Firearm Use Enhancement)',
    sourceUrl: caLeginfo('PEN', '12022.5') },
  { chargeId: 'ca-drug-school-zone-enhancement',
    citation: 'Cal. Health & Safety Code § 11353.6',
    confidence: 'medium', source: 'California Legislature — Health & Safety Code § 11353.6 (Drug offense within 1,000 ft of school)',
    sourceUrl: caLeginfo('HSC', '11353.6') },
  { chargeId: 'ca-rico-organized-crime',
    citation: 'Cal. Penal Code § 186.11',
    confidence: 'medium', source: 'California Legislature — Penal Code § 186.11 (Aggravated White Collar Crime)',
    sourceUrl: caLeginfo('PEN', '186.11') },
  { chargeId: 'ca-money-laundering',
    citation: 'Cal. Penal Code § 186.10',
    confidence: 'medium', source: 'California Legislature — Penal Code § 186.10',
    sourceUrl: caLeginfo('PEN', '186.10') },
  // ── Juvenile ──
  { chargeId: 'ca-juvenile-delinquency-felony',
    citation: 'Cal. Welf. & Inst. Code § 602',
    confidence: 'medium', source: 'California Legislature — Welfare & Institutions Code § 602',
    sourceUrl: caLeginfo('WIC', '602') },
  { chargeId: 'ca-juvenile-delinquency-misdemeanor',
    citation: 'Cal. Welf. & Inst. Code § 602',
    confidence: 'medium', source: 'California Legislature — Welfare & Institutions Code § 602',
    sourceUrl: caLeginfo('WIC', '602') },
  { chargeId: 'ca-juvenile-transfer-adult-court',
    citation: 'Cal. Welf. & Inst. Code § 707(a)',
    confidence: 'medium', source: 'California Legislature — Welfare & Institutions Code § 707 (Transfer to adult court)',
    sourceUrl: caLeginfo('WIC', '707') },
  { chargeId: 'ca-juvenile-firearm-possession',
    citation: 'Cal. Penal Code § 29820(b)',
    confidence: 'medium', source: 'California Legislature — Penal Code § 29820 (Minor in possession of concealable firearm)',
    sourceUrl: caLeginfo('PEN', '29820') },
];

// ── TX MAPPING ────────────────────────────────────────────────────────────────
// Source: Texas Legislature Online (statutes.capitol.texas.gov)
// TPC = Texas Penal Code, TTC = Transportation Code, HSC = Health & Safety Code

const TX_CITATIONS: CitationEntry[] = [
  // ── Homicide ──
  { chargeId: 'tx-murder-in-the-first-degree',
    citation: 'Tex. Penal Code § 19.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 19.02 (Murder)',
    sourceUrl: txUrl('PE', '19') },
  { chargeId: 'tx-murder-in-the-second-degree',
    citation: 'Tex. Penal Code § 19.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 19.02',
    sourceUrl: txUrl('PE', '19') },
  { chargeId: 'tx-capital-murder',
    citation: 'Tex. Penal Code § 19.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 19.03 (Capital Murder)',
    sourceUrl: txUrl('PE', '19') },
  { chargeId: 'tx-voluntary-manslaughter',
    citation: 'Tex. Penal Code § 19.04',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 19.04 (Manslaughter)',
    sourceUrl: txUrl('PE', '19') },
  { chargeId: 'tx-involuntary-manslaughter',
    citation: 'Tex. Penal Code § 19.04',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 19.04 (Manslaughter)',
    sourceUrl: txUrl('PE', '19') },
  { chargeId: 'tx-criminally-negligent-homicide',
    citation: 'Tex. Penal Code § 19.05',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 19.05',
    sourceUrl: txUrl('PE', '19') },
  { chargeId: 'tx-vehicular-homicide',
    citation: 'Tex. Penal Code § 49.08',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 49.08 (Intoxication Manslaughter)',
    sourceUrl: txUrl('PE', '49') },
  { chargeId: 'tx-felony-murder',
    citation: 'Tex. Penal Code § 19.02(b)(3)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 19.02(b)(3)',
    sourceUrl: txUrl('PE', '19') },
  // ── Assault ──
  { chargeId: 'tx-assault-in-the-first-degree',
    citation: 'Tex. Penal Code § 22.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.02 (Aggravated Assault)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-assault-in-the-second-degree',
    citation: 'Tex. Penal Code § 22.01(a)(1)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.01 (Assault)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-assault-in-the-third-degree',
    citation: 'Tex. Penal Code § 22.01(a)(3)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.01 (Assault)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-aggravated-assault',
    citation: 'Tex. Penal Code § 22.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.02',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-assault-with-deadly-weapon',
    citation: 'Tex. Penal Code § 22.02(a)(2)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.02(a)(2)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-domestic-violence-assault',
    citation: 'Tex. Penal Code § 22.01(a)(1)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.01 (Family Violence)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-assault-bodily-injury-family',
    citation: 'Tex. Penal Code § 22.01(a)(1)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.01(a)(1) (Assault Bodily Injury, Family Violence)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-assault-on-peace-officer',
    citation: 'Tex. Penal Code § 22.01(b)(1)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.01(b)(1)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-menacing',
    citation: 'Tex. Penal Code § 22.07',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.07 (Terroristic Threat)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-terroristic-threat',
    citation: 'Tex. Penal Code § 22.07',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.07',
    sourceUrl: txUrl('PE', '22') },
  // ── Sex offenses ──
  { chargeId: 'tx-rape-in-the-first-degree',
    citation: 'Tex. Penal Code § 22.021',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.021 (Aggravated Sexual Assault)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-sexual-assault-in-the-first-degree',
    citation: 'Tex. Penal Code § 22.021',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.021',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-sexual-assault-in-the-second-degree',
    citation: 'Tex. Penal Code § 22.011',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.011 (Sexual Assault)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-statutory-rape',
    citation: 'Tex. Penal Code § 22.011(a)(2)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 22.011(a)(2)',
    sourceUrl: txUrl('PE', '22') },
  { chargeId: 'tx-child-sexual-abuse',
    citation: 'Tex. Penal Code § 21.11',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 21.11 (Indecency with a Child)',
    sourceUrl: txUrl('PE', '21') },
  { chargeId: 'tx-sexual-exploitation-of-minor',
    citation: 'Tex. Penal Code § 43.25',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 43.25',
    sourceUrl: txUrl('PE', '43') },
  // ── Theft ──
  { chargeId: 'tx-grand-theft-in-the-first-degree',
    citation: 'Tex. Penal Code § 31.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 31.03 (Theft)',
    sourceUrl: txUrl('PE', '31') },
  { chargeId: 'tx-petty-theft',
    citation: 'Tex. Penal Code § 31.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 31.03',
    sourceUrl: txUrl('PE', '31') },
  { chargeId: 'tx-theft-under-2500',
    citation: 'Tex. Penal Code § 31.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 31.03',
    sourceUrl: txUrl('PE', '31') },
  { chargeId: 'tx-shoplifting',
    citation: 'Tex. Penal Code § 31.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 31.03',
    sourceUrl: txUrl('PE', '31') },
  { chargeId: 'tx-theft-by-receiving',
    citation: 'Tex. Penal Code § 31.03(a)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 31.03',
    sourceUrl: txUrl('PE', '31') },
  { chargeId: 'tx-embezzlement',
    citation: 'Tex. Penal Code § 31.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 31.03',
    sourceUrl: txUrl('PE', '31') },
  { chargeId: 'tx-identity-theft',
    citation: 'Tex. Penal Code § 32.51',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 32.51',
    sourceUrl: txUrl('PE', '32') },
  { chargeId: 'tx-credit-card-fraud',
    citation: 'Tex. Penal Code § 32.31',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 32.31',
    sourceUrl: txUrl('PE', '32') },
  { chargeId: 'tx-check-fraud',
    citation: 'Tex. Penal Code § 32.41',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 32.41',
    sourceUrl: txUrl('PE', '32') },
  { chargeId: 'tx-forgery',
    citation: 'Tex. Penal Code § 32.21',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 32.21',
    sourceUrl: txUrl('PE', '32') },
  { chargeId: 'tx-insurance-fraud',
    citation: 'Tex. Penal Code § 35.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 35.02',
    sourceUrl: txUrl('PE', '35') },
  { chargeId: 'tx-computer-fraud',
    citation: 'Tex. Penal Code § 33.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 33.02',
    sourceUrl: txUrl('PE', '33') },
  { chargeId: 'tx-wire-fraud',
    citation: 'Tex. Penal Code § 32.46',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 32.46 (Securing Execution of Document by Deception; federal wire fraud = 18 U.S.C. § 1343)',
    sourceUrl: txUrl('PE', '32') },
  { chargeId: 'tx-mail-fraud',
    citation: 'Tex. Penal Code § 32.46',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 32.46 (state analog; federal mail fraud = 18 U.S.C. § 1341)',
    sourceUrl: txUrl('PE', '32') },
  { chargeId: 'tx-tax-fraud',
    citation: 'Tex. Tax Code § 171.212',
    confidence: 'medium', source: 'Texas Legislature — Tax Code § 171.212',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/TX/htm/TX.171.htm' },
  // ── Burglary / Robbery ──
  { chargeId: 'tx-burglary-in-the-first-degree',
    citation: 'Tex. Penal Code § 30.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 30.02 (Burglary)',
    sourceUrl: txUrl('PE', '30') },
  { chargeId: 'tx-burglary-in-the-second-degree',
    citation: 'Tex. Penal Code § 30.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 30.02',
    sourceUrl: txUrl('PE', '30') },
  { chargeId: 'tx-residential-burglary',
    citation: 'Tex. Penal Code § 30.02(a)(1)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 30.02(a)(1)',
    sourceUrl: txUrl('PE', '30') },
  { chargeId: 'tx-commercial-burglary',
    citation: 'Tex. Penal Code § 30.02(a)(2)',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 30.02(a)(2)',
    sourceUrl: txUrl('PE', '30') },
  { chargeId: 'tx-auto-burglary',
    citation: 'Tex. Penal Code § 30.04',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 30.04 (Burglary of Vehicles)',
    sourceUrl: txUrl('PE', '30') },
  { chargeId: 'tx-robbery-in-the-first-degree',
    citation: 'Tex. Penal Code § 29.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 29.03 (Aggravated Robbery)',
    sourceUrl: txUrl('PE', '29') },
  { chargeId: 'tx-robbery-in-the-second-degree',
    citation: 'Tex. Penal Code § 29.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 29.02 (Robbery)',
    sourceUrl: txUrl('PE', '29') },
  { chargeId: 'tx-bank-robbery',
    citation: '18 U.S.C. § 2113',
    confidence: 'medium', source: 'Federal statute — bank robbery prosecuted under federal law',
    sourceUrl: 'https://www.law.cornell.edu/uscode/text/18/2113' },
  { chargeId: 'tx-carjacking',
    citation: 'Tex. Penal Code § 29.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 29.03 (Aggravated Robbery)',
    sourceUrl: txUrl('PE', '29') },
  // ── Drugs ──
  { chargeId: 'tx-possession-of-controlled-substance',
    citation: 'Tex. Health & Safety Code § 481.115',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.115',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  { chargeId: 'tx-possession-with-intent-to-distribute',
    citation: 'Tex. Health & Safety Code § 481.112',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.112',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  { chargeId: 'tx-distribution-of-controlled-substance',
    citation: 'Tex. Health & Safety Code § 481.112',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.112',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  { chargeId: 'tx-manufacturing-controlled-substance',
    citation: 'Tex. Health & Safety Code § 481.112',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.112',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  { chargeId: 'tx-drug-trafficking',
    citation: 'Tex. Health & Safety Code § 481.112',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.112',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  { chargeId: 'tx-possession-of-drug-paraphernalia',
    citation: 'Tex. Health & Safety Code § 481.125',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.125',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  { chargeId: 'tx-possession-of-marijuana',
    citation: 'Tex. Health & Safety Code § 481.121',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.121',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  { chargeId: 'tx-maintaining-drug-house',
    citation: 'Tex. Health & Safety Code § 481.122',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.122',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  // ── Weapons ──
  { chargeId: 'tx-unlawful-carrying-of-weapon',
    citation: 'Tex. Penal Code § 46.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 46.02',
    sourceUrl: txUrl('PE', '46') },
  { chargeId: 'tx-felon-in-possession-of-firearm',
    citation: 'Tex. Penal Code § 46.04',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 46.04',
    sourceUrl: txUrl('PE', '46') },
  { chargeId: 'tx-discharge-of-firearm-in-city',
    citation: 'Tex. Penal Code § 42.12',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 42.12 (Discharge of Firearm in Certain Municipalities)',
    sourceUrl: txUrl('PE', '42') },
  { chargeId: 'tx-possession-of-prohibited-weapon',
    citation: 'Tex. Penal Code § 46.05',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 46.05',
    sourceUrl: txUrl('PE', '46') },
  // ── Public order ──
  { chargeId: 'tx-disorderly-conduct',
    citation: 'Tex. Penal Code § 42.01',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 42.01',
    sourceUrl: txUrl('PE', '42') },
  { chargeId: 'tx-public-intoxication',
    citation: 'Tex. Penal Code § 49.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 49.02',
    sourceUrl: txUrl('PE', '49') },
  { chargeId: 'tx-criminal-trespass',
    citation: 'Tex. Penal Code § 30.05',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 30.05',
    sourceUrl: txUrl('PE', '30') },
  { chargeId: 'tx-criminal-mischief',
    citation: 'Tex. Penal Code § 28.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 28.03 (Criminal Mischief / Vandalism)',
    sourceUrl: txUrl('PE', '28') },
  { chargeId: 'tx-harassment',
    citation: 'Tex. Penal Code § 42.07',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 42.07',
    sourceUrl: txUrl('PE', '42') },
  { chargeId: 'tx-loitering',
    citation: 'Tex. Penal Code § 42.01',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 42.01 (Disorderly Conduct covers loitering)',
    sourceUrl: txUrl('PE', '42') },
  { chargeId: 'tx-solicitation',
    citation: 'Tex. Penal Code § 43.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 43.02 (Prostitution)',
    sourceUrl: txUrl('PE', '43') },
  { chargeId: 'tx-open-container',
    citation: 'Tex. Penal Code § 49.031',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 49.031',
    sourceUrl: txUrl('PE', '49') },
  { chargeId: 'tx-minor-in-possession',
    citation: 'Tex. Alco. Bev. Code § 106.04',
    confidence: 'medium', source: 'Texas Legislature — Alcoholic Beverage Code § 106.04',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/AL/htm/AL.106.htm' },
  { chargeId: 'tx-false-info-to-police',
    citation: 'Tex. Penal Code § 37.08',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 37.08',
    sourceUrl: txUrl('PE', '37') },
  { chargeId: 'tx-evading-arrest',
    citation: 'Tex. Penal Code § 38.04',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 38.04',
    sourceUrl: txUrl('PE', '38') },
  { chargeId: 'tx-failure-to-identify',
    citation: 'Tex. Penal Code § 38.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 38.02',
    sourceUrl: txUrl('PE', '38') },
  // ── Traffic ──
  { chargeId: 'tx-dui-first-offense',
    citation: 'Tex. Penal Code § 49.04',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 49.04 (DWI)',
    sourceUrl: txUrl('PE', '49') },
  { chargeId: 'tx-dui-second-offense',
    citation: 'Tex. Penal Code § 49.04',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 49.04 (DWI with prior)',
    sourceUrl: txUrl('PE', '49') },
  { chargeId: 'tx-dui-third-offense',
    citation: 'Tex. Penal Code § 49.04',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 49.04 (DWI, 3rd or more = felony)',
    sourceUrl: txUrl('PE', '49') },
  { chargeId: 'tx-reckless-driving',
    citation: 'Tex. Transp. Code § 545.401',
    confidence: 'medium', source: 'Texas Legislature — Transportation Code § 545.401',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/TN/htm/TN.545.htm' },
  { chargeId: 'tx-hit-and-run',
    citation: 'Tex. Transp. Code § 550.021',
    confidence: 'medium', source: 'Texas Legislature — Transportation Code § 550.021',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/TN/htm/TN.550.htm' },
  { chargeId: 'tx-driving-while-license-invalid',
    citation: 'Tex. Transp. Code § 521.457',
    confidence: 'medium', source: 'Texas Legislature — Transportation Code § 521.457 (DWLI)',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/TN/htm/TN.521.htm' },
  { chargeId: 'tx-driving-without-insurance',
    citation: 'Tex. Transp. Code § 601.051',
    confidence: 'medium', source: 'Texas Legislature — Transportation Code § 601.051',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/TN/htm/TN.601.htm' },
  { chargeId: 'tx-expired-registration',
    citation: 'Tex. Transp. Code § 502.412',
    confidence: 'medium', source: 'Texas Legislature — Transportation Code § 502.412',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/TN/htm/TN.502.htm' },
  // ── Procedural ──
  { chargeId: 'tx-failure-to-appear',
    citation: 'Tex. Penal Code § 38.10',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 38.10',
    sourceUrl: txUrl('PE', '38') },
  { chargeId: 'tx-probation-violation',
    citation: 'Tex. Code Crim. Proc. art. 42A.751',
    confidence: 'medium', source: 'Texas Legislature — Code of Criminal Procedure Art. 42A.751',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/CR/htm/CR.42A.htm' },
  { chargeId: 'tx-resisting-arrest',
    citation: 'Tex. Penal Code § 38.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 38.03',
    sourceUrl: txUrl('PE', '38') },
  { chargeId: 'tx-protective-order-violation',
    citation: 'Tex. Penal Code § 25.07',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 25.07',
    sourceUrl: txUrl('PE', '25') },
  { chargeId: 'tx-contempt-of-court',
    citation: 'Tex. Gov\'t Code § 21.002',
    confidence: 'medium', source: 'Texas Legislature — Government Code § 21.002',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/GV/htm/GV.21.htm' },
  // ── Attempt / conspiracy / complicity ──
  { chargeId: 'tx-criminal-attempt',
    citation: 'Tex. Penal Code § 15.01',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 15.01 (Criminal Attempt)',
    sourceUrl: txUrl('PE', '15') },
  { chargeId: 'tx-conspiracy',
    citation: 'Tex. Penal Code § 15.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 15.02',
    sourceUrl: txUrl('PE', '15') },
  { chargeId: 'tx-aiding-and-abetting',
    citation: 'Tex. Penal Code § 7.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 7.02 (Criminal Responsibility for Conduct of Another)',
    sourceUrl: txUrl('PE', '7') },
  { chargeId: 'tx-accessory-after-the-fact',
    citation: 'Tex. Penal Code § 38.05',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 38.05 (Hindering Apprehension)',
    sourceUrl: txUrl('PE', '38') },
  { chargeId: 'tx-criminal-solicitation',
    citation: 'Tex. Penal Code § 15.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 15.03',
    sourceUrl: txUrl('PE', '15') },
  { chargeId: 'tx-attempted-murder',
    citation: 'Tex. Penal Code §§ 15.01, 19.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code §§ 15.01, 19.02',
    sourceUrl: txUrl('PE', '15') },
  { chargeId: 'tx-attempted-robbery',
    citation: 'Tex. Penal Code §§ 15.01, 29.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code §§ 15.01, 29.02',
    sourceUrl: txUrl('PE', '15') },
  { chargeId: 'tx-attempted-sexual-assault',
    citation: 'Tex. Penal Code §§ 15.01, 22.011',
    confidence: 'medium', source: 'Texas Legislature — Penal Code §§ 15.01, 22.011',
    sourceUrl: txUrl('PE', '15') },
  // ── Enhancements ──
  { chargeId: 'tx-gang-enhancement',
    citation: 'Tex. Penal Code § 71.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 71.02 (Engaging in Organized Criminal Activity)',
    sourceUrl: txUrl('PE', '71') },
  { chargeId: 'tx-hate-crime-enhancement',
    citation: 'Tex. Penal Code § 12.47',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 12.47 (Penalty If Offense Committed Because of Bias)',
    sourceUrl: txUrl('PE', '12') },
  { chargeId: 'tx-recidivist-enhancement',
    citation: 'Tex. Penal Code § 12.42',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 12.42 (Penalties for Repeat Felony Offenders)',
    sourceUrl: txUrl('PE', '12') },
  { chargeId: 'tx-firearm-in-felony-enhancement',
    citation: 'Tex. Penal Code § 46.03',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 46.03 (Places Weapons Prohibited)',
    sourceUrl: txUrl('PE', '46') },
  { chargeId: 'tx-drug-school-zone-enhancement',
    citation: 'Tex. Health & Safety Code § 481.134',
    confidence: 'medium', source: 'Texas Legislature — Health & Safety Code § 481.134 (Drug Free Zone)',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm' },
  { chargeId: 'tx-rico-organized-crime',
    citation: 'Tex. Penal Code § 71.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 71.02 (Organized Criminal Activity)',
    sourceUrl: txUrl('PE', '71') },
  { chargeId: 'tx-money-laundering',
    citation: 'Tex. Penal Code § 34.02',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 34.02',
    sourceUrl: txUrl('PE', '34') },
  // ── Juvenile ──
  { chargeId: 'tx-juvenile-delinquency-felony',
    citation: 'Tex. Fam. Code § 51.03',
    confidence: 'medium', source: 'Texas Legislature — Family Code § 51.03 (Delinquent Conduct)',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/FA/htm/FA.51.htm' },
  { chargeId: 'tx-juvenile-delinquency-misdemeanor',
    citation: 'Tex. Fam. Code § 51.03',
    confidence: 'medium', source: 'Texas Legislature — Family Code § 51.03',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/FA/htm/FA.51.htm' },
  { chargeId: 'tx-juvenile-transfer-adult-court',
    citation: 'Tex. Fam. Code § 54.02',
    confidence: 'medium', source: 'Texas Legislature — Family Code § 54.02 (Waiver of Jurisdiction)',
    sourceUrl: 'https://statutes.capitol.texas.gov/Docs/FA/htm/FA.54.htm' },
  { chargeId: 'tx-juvenile-firearm-possession',
    citation: 'Tex. Penal Code § 46.13',
    confidence: 'medium', source: 'Texas Legislature — Penal Code § 46.13 (Making a Firearm Accessible to a Child)',
    sourceUrl: txUrl('PE', '46') },
];

// ── IL MAPPING ────────────────────────────────────────────────────────────────
// Source: Illinois General Assembly (ilga.gov) + Justia Illinois
// 720 ILCS 5 = Criminal Code of 2012
// 625 ILCS 5 = Illinois Vehicle Code
// 720 ILCS 570 = Illinois Controlled Substances Act
// 730 ILCS 5 = Unified Code of Corrections (sentencing/probation)

const IL_CITATIONS: CitationEntry[] = [
  // ── Homicide ──
  { chargeId: 'il-murder-in-the-first-degree',
    citation: '720 ILCS 5/9-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/9-1 (First Degree Murder)',
    sourceUrl: ilJustia('720', '5', '9-1') },
  { chargeId: 'il-murder-in-the-second-degree',
    citation: '720 ILCS 5/9-2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/9-2 (Second Degree Murder)',
    sourceUrl: ilJustia('720', '5', '9-2') },
  { chargeId: 'il-voluntary-manslaughter',
    citation: '720 ILCS 5/9-2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/9-2',
    sourceUrl: ilJustia('720', '5', '9-2') },
  { chargeId: 'il-involuntary-manslaughter',
    citation: '720 ILCS 5/9-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/9-3 (Involuntary Manslaughter)',
    sourceUrl: ilJustia('720', '5', '9-3') },
  { chargeId: 'il-criminally-negligent-homicide',
    citation: '720 ILCS 5/9-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/9-3',
    sourceUrl: ilJustia('720', '5', '9-3') },
  { chargeId: 'il-vehicular-homicide',
    citation: '720 ILCS 5/9-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/9-3 (Reckless Homicide)',
    sourceUrl: ilJustia('720', '5', '9-3') },
  { chargeId: 'il-felony-murder',
    citation: '720 ILCS 5/9-1(a)(3)',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/9-1(a)(3) (Felony Murder)',
    sourceUrl: ilJustia('720', '5', '9-1') },
  // ── Assault ──
  { chargeId: 'il-assault-in-the-first-degree',
    citation: '720 ILCS 5/12-3.05',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-3.05 (Aggravated Battery)',
    sourceUrl: ilJustia('720', '5', '12-3.05') },
  { chargeId: 'il-assault-in-the-second-degree',
    citation: '720 ILCS 5/12-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-3 (Battery)',
    sourceUrl: ilJustia('720', '5', '12-3') },
  { chargeId: 'il-assault-in-the-third-degree',
    citation: '720 ILCS 5/12-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-1 (Assault)',
    sourceUrl: ilJustia('720', '5', '12-1') },
  { chargeId: 'il-aggravated-assault',
    citation: '720 ILCS 5/12-2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-2 (Aggravated Assault)',
    sourceUrl: ilJustia('720', '5', '12-2') },
  { chargeId: 'il-assault-with-deadly-weapon',
    citation: '720 ILCS 5/12-3.05(f)(1)',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-3.05(f)(1)',
    sourceUrl: ilJustia('720', '5', '12-3.05') },
  { chargeId: 'il-domestic-violence-assault',
    citation: '720 ILCS 5/12-3.2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-3.2 (Domestic Battery)',
    sourceUrl: ilJustia('720', '5', '12-3.2') },
  { chargeId: 'il-assault-on-peace-officer',
    citation: '720 ILCS 5/12-2(b)(4)',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-2(b)(4)',
    sourceUrl: ilJustia('720', '5', '12-2') },
  { chargeId: 'il-menacing',
    citation: '720 ILCS 5/12-9',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-9 (Threatening a Public Official) or 720 ILCS 5/12-6 (Intimidation)',
    sourceUrl: ilJustia('720', '5', '12-6') },
  // ── Sex offenses ──
  { chargeId: 'il-rape-in-the-first-degree',
    citation: '720 ILCS 5/11-1.20',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/11-1.20 (Aggravated Criminal Sexual Assault)',
    sourceUrl: ilJustia('720', '5', '11-1.20') },
  { chargeId: 'il-sexual-assault-in-the-second-degree',
    citation: '720 ILCS 5/11-1.30',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/11-1.30 (Predatory Criminal Sexual Assault)',
    sourceUrl: ilJustia('720', '5', '11-1.30') },
  { chargeId: 'il-sexual-assault-in-the-third-degree',
    citation: '720 ILCS 5/11-1.50',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/11-1.50 (Criminal Sexual Abuse)',
    sourceUrl: ilJustia('720', '5', '11-1.50') },
  { chargeId: 'il-statutory-rape',
    citation: '720 ILCS 5/11-1.60',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/11-1.60 (Aggravated Criminal Sexual Abuse)',
    sourceUrl: ilJustia('720', '5', '11-1.60') },
  { chargeId: 'il-child-sexual-abuse',
    citation: '720 ILCS 5/11-1.40',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/11-1.40 (Predatory Criminal Sexual Assault of a Child)',
    sourceUrl: ilJustia('720', '5', '11-1.40') },
  { chargeId: 'il-sexual-exploitation-of-minor',
    citation: '720 ILCS 5/11-9.1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/11-9.1',
    sourceUrl: ilJustia('720', '5', '11-9.1') },
  // ── Theft / Property ──
  { chargeId: 'il-grand-theft-in-the-first-degree',
    citation: '720 ILCS 5/16-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/16-1 (Theft)',
    sourceUrl: ilJustia('720', '5', '16-1') },
  { chargeId: 'il-grand-theft-in-the-second-degree',
    citation: '720 ILCS 5/16-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/16-1',
    sourceUrl: ilJustia('720', '5', '16-1') },
  { chargeId: 'il-petty-theft',
    citation: '720 ILCS 5/16-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/16-1',
    sourceUrl: ilJustia('720', '5', '16-1') },
  { chargeId: 'il-shoplifting',
    citation: '720 ILCS 5/16-25',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/16-25 (Retail Theft)',
    sourceUrl: ilJustia('720', '5', '16-25') },
  { chargeId: 'il-theft-by-receiving',
    citation: '720 ILCS 5/16-1(a)(4)',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/16-1(a)(4)',
    sourceUrl: ilJustia('720', '5', '16-1') },
  { chargeId: 'il-identity-theft',
    citation: '720 ILCS 5/16-30',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/16-30 (Identity Theft)',
    sourceUrl: ilJustia('720', '5', '16-30') },
  { chargeId: 'il-credit-card-fraud',
    citation: '720 ILCS 5/17-32',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/17-32',
    sourceUrl: ilJustia('720', '5', '17-32') },
  { chargeId: 'il-embezzlement',
    citation: '720 ILCS 5/16-1(a)(2)',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/16-1(a)(2)',
    sourceUrl: ilJustia('720', '5', '16-1') },
  { chargeId: 'il-forgery',
    citation: '720 ILCS 5/17-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/17-3 (Forgery)',
    sourceUrl: ilJustia('720', '5', '17-3') },
  { chargeId: 'il-check-fraud',
    citation: '720 ILCS 5/17-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/17-1',
    sourceUrl: ilJustia('720', '5', '17-1') },
  { chargeId: 'il-bad-checks',
    citation: '720 ILCS 5/17-1(B)',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/17-1(B)',
    sourceUrl: ilJustia('720', '5', '17-1') },
  { chargeId: 'il-insurance-fraud',
    citation: '720 ILCS 5/17-10.5',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/17-10.5',
    sourceUrl: ilJustia('720', '5', '17-10.5') },
  { chargeId: 'il-computer-fraud',
    citation: '720 ILCS 5/17-51',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/17-51 (Computer Fraud)',
    sourceUrl: ilJustia('720', '5', '17-51') },
  { chargeId: 'il-wire-fraud',
    citation: '720 ILCS 5/17-24',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/17-24 (Electronic Fraud; federal wire fraud = 18 U.S.C. § 1343)',
    sourceUrl: ilJustia('720', '5', '17-24') },
  { chargeId: 'il-mail-fraud',
    citation: '720 ILCS 5/17-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/17-3 (state analog; federal mail fraud = 18 U.S.C. § 1341)',
    sourceUrl: ilJustia('720', '5', '17-3') },
  { chargeId: 'il-tax-fraud',
    citation: '35 ILCS 5/1301',
    confidence: 'medium', source: 'Illinois General Assembly — 35 ILCS 5/1301 (Illinois Income Tax Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs4.asp?ActID=596&ChapterID=8' },
  { chargeId: 'il-fake-id',
    citation: '625 ILCS 5/6-301.2',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/6-301.2 (Fraudulent ID)',
    sourceUrl: ilJustia('625', '5', '6-301.2') },
  // ── Burglary / Robbery ──
  { chargeId: 'il-burglary-in-the-first-degree',
    citation: '720 ILCS 5/19-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/19-1 (Burglary)',
    sourceUrl: ilJustia('720', '5', '19-1') },
  { chargeId: 'il-burglary-in-the-second-degree',
    citation: '720 ILCS 5/19-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/19-1',
    sourceUrl: ilJustia('720', '5', '19-1') },
  { chargeId: 'il-residential-burglary',
    citation: '720 ILCS 5/19-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/19-3 (Residential Burglary)',
    sourceUrl: ilJustia('720', '5', '19-3') },
  { chargeId: 'il-auto-burglary',
    citation: '720 ILCS 5/19-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/19-1',
    sourceUrl: ilJustia('720', '5', '19-1') },
  { chargeId: 'il-robbery-in-the-first-degree',
    citation: '720 ILCS 5/18-2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/18-2 (Armed Robbery)',
    sourceUrl: ilJustia('720', '5', '18-2') },
  { chargeId: 'il-robbery-in-the-second-degree',
    citation: '720 ILCS 5/18-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/18-1 (Robbery)',
    sourceUrl: ilJustia('720', '5', '18-1') },
  { chargeId: 'il-bank-robbery',
    citation: '18 U.S.C. § 2113',
    confidence: 'medium', source: 'Federal statute — bank robbery',
    sourceUrl: 'https://www.law.cornell.edu/uscode/text/18/2113' },
  { chargeId: 'il-carjacking',
    citation: '720 ILCS 5/18-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/18-3 (Vehicular Invasion)',
    sourceUrl: ilJustia('720', '5', '18-3') },
  // ── Drugs ──
  { chargeId: 'il-possession-of-controlled-substance',
    citation: '720 ILCS 570/402',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 570/402 (Possession of Controlled Substance)',
    sourceUrl: 'https://law.justia.com/codes/illinois/chapter-720/act-570/section-570-402/' },
  { chargeId: 'il-possession-with-intent-to-distribute',
    citation: '720 ILCS 570/401',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 570/401 (Manufacture / Delivery)',
    sourceUrl: 'https://law.justia.com/codes/illinois/chapter-720/act-570/section-570-401/' },
  { chargeId: 'il-distribution-of-controlled-substance',
    citation: '720 ILCS 570/401',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 570/401',
    sourceUrl: 'https://law.justia.com/codes/illinois/chapter-720/act-570/section-570-401/' },
  { chargeId: 'il-manufacturing-controlled-substance',
    citation: '720 ILCS 570/401',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 570/401',
    sourceUrl: 'https://law.justia.com/codes/illinois/chapter-720/act-570/section-570-401/' },
  { chargeId: 'il-drug-trafficking',
    citation: '720 ILCS 570/401',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 570/401',
    sourceUrl: 'https://law.justia.com/codes/illinois/chapter-720/act-570/section-570-401/' },
  { chargeId: 'il-possession-of-drug-paraphernalia',
    citation: '720 ILCS 600/3.5',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 600/3.5 (Drug Paraphernalia Control Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1941' },
  { chargeId: 'il-maintaining-drug-house',
    citation: '720 ILCS 570/406.2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 570/406.2',
    sourceUrl: 'https://law.justia.com/codes/illinois/chapter-720/act-570/section-570-406.2/' },
  // ── Weapons ──
  { chargeId: 'il-unlawful-carrying-of-weapon',
    citation: '720 ILCS 5/24-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/24-1 (Unlawful Use of Weapons)',
    sourceUrl: ilJustia('720', '5', '24-1') },
  { chargeId: 'il-felon-in-possession-of-firearm',
    citation: '720 ILCS 5/24-1.1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/24-1.1 (Unlawful Use or Possession by Felon)',
    sourceUrl: ilJustia('720', '5', '24-1.1') },
  { chargeId: 'il-discharge-of-firearm-in-city',
    citation: '720 ILCS 5/24-1.2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/24-1.2 (Aggravated Discharge of a Firearm)',
    sourceUrl: ilJustia('720', '5', '24-1.2') },
  { chargeId: 'il-possession-of-prohibited-weapon',
    citation: '720 ILCS 5/24-1(a)',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/24-1(a) (Unlawful Use of Weapons)',
    sourceUrl: ilJustia('720', '5', '24-1') },
  // ── Public order ──
  { chargeId: 'il-disorderly-conduct',
    citation: '720 ILCS 5/26-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/26-1',
    sourceUrl: ilJustia('720', '5', '26-1') },
  { chargeId: 'il-public-intoxication',
    citation: '720 ILCS 5/26-5',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/26-5',
    sourceUrl: ilJustia('720', '5', '26-5') },
  { chargeId: 'il-criminal-trespass-to-real-property',
    citation: '720 ILCS 5/21-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/21-3',
    sourceUrl: ilJustia('720', '5', '21-3') },
  { chargeId: 'il-trespassing',
    citation: '720 ILCS 5/21-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/21-3',
    sourceUrl: ilJustia('720', '5', '21-3') },
  { chargeId: 'il-trespass-after-warning',
    citation: '720 ILCS 5/21-3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/21-3',
    sourceUrl: ilJustia('720', '5', '21-3') },
  { chargeId: 'il-vandalism',
    citation: '720 ILCS 5/21-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/21-1 (Criminal Damage to Property)',
    sourceUrl: ilJustia('720', '5', '21-1') },
  { chargeId: 'il-criminal-mischief',
    citation: '720 ILCS 5/21-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/21-1',
    sourceUrl: ilJustia('720', '5', '21-1') },
  { chargeId: 'il-loitering',
    citation: '720 ILCS 5/26-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/26-1 (Disorderly Conduct covers loitering)',
    sourceUrl: ilJustia('720', '5', '26-1') },
  { chargeId: 'il-indecent-exposure',
    citation: '720 ILCS 5/11-30',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/11-30 (Public Indecency)',
    sourceUrl: ilJustia('720', '5', '11-30') },
  { chargeId: 'il-noise-violation',
    citation: '720 ILCS 5/26-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/26-1',
    sourceUrl: ilJustia('720', '5', '26-1') },
  { chargeId: 'il-panhandling',
    citation: '720 ILCS 5/26-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/26-1 (Disorderly Conduct)',
    sourceUrl: ilJustia('720', '5', '26-1') },
  { chargeId: 'il-illegal-camping',
    citation: '720 ILCS 5/26-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/26-1 (municipal ordinances may also apply)',
    sourceUrl: ilJustia('720', '5', '26-1') },
  { chargeId: 'il-harassment',
    citation: '720 ILCS 5/12-7.3',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-7.3 (Stalking)',
    sourceUrl: ilJustia('720', '5', '12-7.3') },
  { chargeId: 'il-solicitation',
    citation: '720 ILCS 5/11-14',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/11-14 (Prostitution)',
    sourceUrl: ilJustia('720', '5', '11-14') },
  { chargeId: 'il-animal-cruelty-misdemeanor',
    citation: '510 ILCS 70/3.01',
    confidence: 'medium', source: 'Illinois General Assembly — 510 ILCS 70/3.01 (Humane Care for Animals Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1717' },
  { chargeId: 'il-illegal-fireworks',
    citation: '425 ILCS 35/2',
    confidence: 'medium', source: 'Illinois General Assembly — 425 ILCS 35/2 (Pyrotechnic Use Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1455' },
  { chargeId: 'il-littering',
    citation: '415 ILCS 105/4',
    confidence: 'medium', source: 'Illinois General Assembly — 415 ILCS 105/4 (Litter Control Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1422' },
  // ── Traffic ──
  { chargeId: 'il-dui-first-offense',
    citation: '625 ILCS 5/11-501',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/11-501 (DUI)',
    sourceUrl: ilJustia('625', '5', '11-501') },
  { chargeId: 'il-dui-second-offense',
    citation: '625 ILCS 5/11-501',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/11-501',
    sourceUrl: ilJustia('625', '5', '11-501') },
  { chargeId: 'il-dui-third-offense',
    citation: '625 ILCS 5/11-501',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/11-501',
    sourceUrl: ilJustia('625', '5', '11-501') },
  { chargeId: 'il-reckless-driving-criminal',
    citation: '625 ILCS 5/11-503',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/11-503 (Reckless Driving)',
    sourceUrl: ilJustia('625', '5', '11-503') },
  { chargeId: 'il-reckless-driving',
    citation: '625 ILCS 5/11-503',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/11-503',
    sourceUrl: ilJustia('625', '5', '11-503') },
  { chargeId: 'il-hit-and-run',
    citation: '625 ILCS 5/11-401',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/11-401',
    sourceUrl: ilJustia('625', '5', '11-401') },
  { chargeId: 'il-driving-while-suspended',
    citation: '625 ILCS 5/6-303',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/6-303',
    sourceUrl: ilJustia('625', '5', '6-303') },
  { chargeId: 'il-driving-without-license',
    citation: '625 ILCS 5/6-101',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/6-101',
    sourceUrl: ilJustia('625', '5', '6-101') },
  { chargeId: 'il-driving-without-insurance',
    citation: '625 ILCS 5/3-707',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/3-707',
    sourceUrl: ilJustia('625', '5', '3-707') },
  { chargeId: 'il-expired-registration',
    citation: '625 ILCS 5/3-701',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/3-701',
    sourceUrl: ilJustia('625', '5', '3-701') },
  { chargeId: 'il-expired-inspection',
    citation: '625 ILCS 5/13-101',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/13-101',
    sourceUrl: ilJustia('625', '5', '13-101') },
  { chargeId: 'il-open-container',
    citation: '625 ILCS 5/11-502',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/11-502 (Open Container)',
    sourceUrl: ilJustia('625', '5', '11-502') },
  { chargeId: 'il-defective-vehicle-equipment',
    citation: '625 ILCS 5/12-201',
    confidence: 'medium', source: 'Illinois General Assembly — 625 ILCS 5/12-201',
    sourceUrl: ilJustia('625', '5', '12-201') },
  // ── Miscellaneous ──
  { chargeId: 'il-contempt-of-court',
    citation: '720 ILCS 5/32-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/32-1',
    sourceUrl: ilJustia('720', '5', '32-1') },
  { chargeId: 'il-failure-to-appear',
    citation: '725 ILCS 5/110-4',
    confidence: 'medium', source: 'Illinois General Assembly — 725 ILCS 5/110-4',
    sourceUrl: 'https://law.justia.com/codes/illinois/chapter-725/act-5/section-5-110-4/' },
  { chargeId: 'il-probation-violation',
    citation: '730 ILCS 5/5-6-4',
    confidence: 'medium', source: 'Illinois General Assembly — 730 ILCS 5/5-6-4 (Resentencing after revocation of probation)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs4.asp?ActID=1840' },
  { chargeId: 'il-resisting-arrest',
    citation: '720 ILCS 5/31-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/31-1',
    sourceUrl: ilJustia('720', '5', '31-1') },
  { chargeId: 'il-protective-order-violation',
    citation: '720 ILCS 5/12-3.4',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-3.4 (Violation of Order of Protection)',
    sourceUrl: ilJustia('720', '5', '12-3.4') },
  { chargeId: 'il-failure-to-pay-child-support',
    citation: '750 ILCS 16/15',
    confidence: 'medium', source: 'Illinois General Assembly — 750 ILCS 16/15 (Illinois Non-Support Punishment Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=2086' },
  { chargeId: 'il-minor-in-possession',
    citation: '235 ILCS 5/6-20',
    confidence: 'medium', source: 'Illinois General Assembly — 235 ILCS 5/6-20 (Liquor Control Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=2093' },
  { chargeId: 'il-false-info-to-police',
    citation: '720 ILCS 5/31-4.5',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/31-4.5',
    sourceUrl: ilJustia('720', '5', '31-4.5') },
  { chargeId: 'il-curfew-violation',
    citation: '720 ILCS 555/1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 555/1 (Juvenile Curfew Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1941' },
  { chargeId: 'il-truancy',
    citation: '105 ILCS 26/2-1',
    confidence: 'medium', source: 'Illinois General Assembly — 105 ILCS 26/2-1 (School Attendance and Child Labor Act)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1018' },
  { chargeId: 'il-alcohol-in-park',
    citation: '235 ILCS 5/5-12',
    confidence: 'medium', source: 'Illinois General Assembly — 235 ILCS 5/5-12 (local ordinance may also apply)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=2093' },
  { chargeId: 'il-hunting-fishing-no-license',
    citation: '520 ILCS 5/2.1',
    confidence: 'medium', source: 'Illinois General Assembly — 520 ILCS 5/2.1 (Wildlife Code)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1749' },
  // ── Attempt / conspiracy / complicity ──
  { chargeId: 'il-criminal-attempt',
    citation: '720 ILCS 5/8-4',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/8-4 (Attempt)',
    sourceUrl: ilJustia('720', '5', '8-4') },
  { chargeId: 'il-conspiracy',
    citation: '720 ILCS 5/8-2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/8-2 (Conspiracy)',
    sourceUrl: ilJustia('720', '5', '8-2') },
  { chargeId: 'il-aiding-and-abetting',
    citation: '720 ILCS 5/5-2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/5-2 (Accountability for Conduct of Another)',
    sourceUrl: ilJustia('720', '5', '5-2') },
  { chargeId: 'il-accessory-after-the-fact',
    citation: '720 ILCS 5/31-5',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/31-5 (Compounding a Crime)',
    sourceUrl: ilJustia('720', '5', '31-5') },
  { chargeId: 'il-criminal-solicitation',
    citation: '720 ILCS 5/8-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/8-1 (Solicitation)',
    sourceUrl: ilJustia('720', '5', '8-1') },
  { chargeId: 'il-attempted-murder',
    citation: '720 ILCS 5/8-4; 720 ILCS 5/9-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/8-4, 9-1',
    sourceUrl: ilJustia('720', '5', '8-4') },
  { chargeId: 'il-attempted-robbery',
    citation: '720 ILCS 5/8-4; 720 ILCS 5/18-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/8-4, 18-1',
    sourceUrl: ilJustia('720', '5', '8-4') },
  { chargeId: 'il-attempted-sexual-assault',
    citation: '720 ILCS 5/8-4; 720 ILCS 5/11-1.20',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/8-4, 11-1.20',
    sourceUrl: ilJustia('720', '5', '8-4') },
  // ── Enhancements ──
  { chargeId: 'il-gang-enhancement',
    citation: '720 ILCS 5/25-5',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/25-5 (Gang Activity)',
    sourceUrl: ilJustia('720', '5', '25-5') },
  { chargeId: 'il-hate-crime-enhancement',
    citation: '720 ILCS 5/12-7.1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/12-7.1 (Hate Crime)',
    sourceUrl: ilJustia('720', '5', '12-7.1') },
  { chargeId: 'il-recidivist-enhancement',
    citation: '730 ILCS 5/5-4.5-95',
    confidence: 'medium', source: 'Illinois General Assembly — 730 ILCS 5/5-4.5-95 (Habitual Criminal)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs4.asp?ActID=1840' },
  { chargeId: 'il-firearm-in-felony-enhancement',
    citation: '720 ILCS 5/33A-2',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/33A-2 (Armed Violence)',
    sourceUrl: ilJustia('720', '5', '33A-2') },
  { chargeId: 'il-drug-school-zone-enhancement',
    citation: '720 ILCS 570/407',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 570/407 (Drug Free Zone)',
    sourceUrl: 'https://law.justia.com/codes/illinois/chapter-720/act-570/section-570-407/' },
  { chargeId: 'il-rico-organized-crime',
    citation: '720 ILCS 5/33G-4',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/33G-4 (Illinois Streetgang Terrorism Omnibus Prevention Act / RICO analog)',
    sourceUrl: ilJustia('720', '5', '33G-4') },
  { chargeId: 'il-money-laundering',
    citation: '720 ILCS 5/29B-1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/29B-1 (Money Laundering)',
    sourceUrl: ilJustia('720', '5', '29B-1') },
  // ── Juvenile ──
  { chargeId: 'il-juvenile-delinquency-felony',
    citation: '705 ILCS 405/5-105',
    confidence: 'medium', source: 'Illinois General Assembly — 705 ILCS 405/5-105 (Juvenile Court Act — Delinquency)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1863' },
  { chargeId: 'il-juvenile-delinquency-misdemeanor',
    citation: '705 ILCS 405/5-105',
    confidence: 'medium', source: 'Illinois General Assembly — 705 ILCS 405/5-105',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1863' },
  { chargeId: 'il-juvenile-transfer-adult-court',
    citation: '705 ILCS 405/5-805',
    confidence: 'medium', source: 'Illinois General Assembly — 705 ILCS 405/5-805 (Transfer to Criminal Court)',
    sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1863' },
  { chargeId: 'il-juvenile-firearm-possession',
    citation: '720 ILCS 5/24-1.1',
    confidence: 'medium', source: 'Illinois General Assembly — 720 ILCS 5/24-1.1',
    sourceUrl: ilJustia('720', '5', '24-1.1') },
];

// ── Overlay writer ────────────────────────────────────────────────────────────

function buildBlock(state: string, entries: CitationEntry[]): string {
  const lines: string[] = [
    '',
    `  // ── ${state}: Official legislature sources — confidence medium — ${VERIFIED_MONTH} ───────────`,
  ];
  for (const e of entries) {
    if (e.skip) continue;
    lines.push(`  "${e.chargeId}": {`);
    lines.push(`    citation: ${JSON.stringify(e.citation)},`);
    lines.push(`    confidence: "medium",`);
    lines.push(`    lastVerified: "${VERIFIED_MONTH}",`);
    lines.push(`    source: ${JSON.stringify(e.source)},`);
    lines.push(`    sourceUrl: ${JSON.stringify(e.sourceUrl)},`);
    lines.push(`  },`);
  }
  return lines.join('\n');
}

function applyToOverlay(overlayPath: string, entries: CitationEntry[], state: string): void {
  let src = fs.readFileSync(overlayPath, 'utf-8');

  // Collect already-existing IDs
  const existingRe = /"([a-z]{2}-[^"]+)":\s*\{/g;
  const existingIds = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = existingRe.exec(src)) !== null) existingIds.add(m[1]);

  // Build a block containing only genuinely new entries
  const newEntries = entries.filter(e => {
    if (e.skip) return false;
    if (existingIds.has(e.chargeId)) {
      console.log(`  skip (already exists): ${e.chargeId}`);
      return false;
    }
    return true;
  });

  if (newEntries.length === 0) {
    console.log(`  (no new entries to insert for ${state})`);
    return; // do NOT rewrite the file — nothing changed
  }

  const newBlock = buildBlock(state, newEntries);
  const insertAt = src.lastIndexOf('\n};');
  if (insertAt === -1) throw new Error('Could not find closing }; in overlay file');
  src = src.slice(0, insertAt) + newBlock + '\n};';
  fs.writeFileSync(overlayPath, src, 'utf-8');
  console.log(`  inserted ${newEntries.length} new entries for ${state}`);
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main(): void {
  const stateMap: Record<string, CitationEntry[]> = {
    CA: CA_CITATIONS,
    TX: TX_CITATIONS,
    IL: IL_CITATIONS,
  };

  const statesToProcess = STATE_FILTER
    ? [STATE_FILTER]
    : ['CA', 'TX', 'IL'];

  for (const state of statesToProcess) {
    if (!stateMap[state]) {
      console.error(`Unknown state: ${state}. Use CA, TX, or IL.`);
      process.exit(1);
    }
  }

  const overlayPath = path.join(process.cwd(), 'shared/criminal-charge-citations.ts');
  const outputDir   = path.join(process.cwd(), 'scripts/data-review/output');
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  console.log(`\nState Citation Generator`);
  console.log(`────────────────────────────────`);
  console.log(`States  : ${statesToProcess.join(', ')}`);
  console.log(`Mode    : ${DRY_RUN ? 'DRY RUN' : APPLY ? 'APPLY to overlay' : 'Output JSON only'}`);
  console.log('');

  for (const state of statesToProcess) {
    const entries = stateMap[state];
    const visible = entries.filter(e => !e.skip);
    console.log(`${state}: ${visible.length} entries`);

    // Write JSON output
    const jsonPath = path.join(outputDir, `${state.toLowerCase()}-citations-output.json`);
    fs.writeFileSync(jsonPath, JSON.stringify({
      state,
      generatedAt: new Date().toISOString(),
      confidence: 'medium',
      entryCount: visible.length,
      entries: visible,
    }, null, 2));
    console.log(`  JSON output: ${jsonPath}`);

    if (DRY_RUN) {
      for (const e of visible) {
        console.log(`  [DRY] ${e.chargeId} → ${e.citation}`);
      }
      continue;
    }

    if (APPLY) {
      applyToOverlay(overlayPath, entries, state);
    }
  }

  if (!APPLY && !DRY_RUN) {
    console.log('\nTo write entries into the overlay, re-run with --apply');
    console.log('Spot-check a sample of entries against the source URLs first.');
    console.log('After review, run promote-verified-citations.ts to promote confirmed entries to "high".');
  }
}

main();
