import fs from "node:fs";
import path from "node:path";
import {
  getNorthCarolinaTitleReviewAction,
} from "../../shared/north-carolina-title-review-actions";

type ReviewDecision = "approve" | "reject" | "pending";

interface ReviewRow {
  chargeId: string;
  catalogLabel: string;
  proposedAlias: string;
  citation: string;
  subdivision: string;
  officialCodeUrl: string;
  approvedDisplayName: string;
  decision: ReviewDecision;
  reviewer: string;
  reviewedAt: string;
  note: string;
}

const inputPath = path.resolve(
  process.cwd(),
  process.argv[2] ?? "docs/north-carolina-title-attorney-review-completed.csv",
);
const outputPath = path.resolve(
  process.cwd(),
  process.argv[3] ?? "server/data/north-carolina-title-attorney-review.ts",
);
const displayNamesPath = path.resolve(
  process.cwd(),
  process.argv[4] ?? "shared/north-carolina-approved-display-names.ts",
);

function parseCsv(input: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;

  for (let index = 0; index < input.length; index += 1) {
    const character = input[index];
    const next = input[index + 1];
    if (character === '"' && quoted && next === '"') {
      field += '"';
      index += 1;
    } else if (character === '"') {
      quoted = !quoted;
    } else if (character === "," && !quoted) {
      row.push(field);
      field = "";
    } else if ((character === "\n" || character === "\r") && !quoted) {
      if (character === "\r" && next === "\n") index += 1;
      row.push(field);
      if (row.some((value) => value.length > 0)) rows.push(row);
      row = [];
      field = "";
    } else {
      field += character;
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function asReviewRow(headers: string[], values: string[]): ReviewRow {
  const row = Object.fromEntries(headers.map((header, index) => [
    header,
    values[index] ?? "",
  ])) as unknown as ReviewRow;
  if (!row.chargeId || !row.catalogLabel || !row.citation || !row.note) {
    throw new Error(`Incomplete North Carolina review row: ${JSON.stringify(row)}`);
  }
  if (!["approve", "reject", "pending"].includes(row.decision)) {
    throw new Error(`Invalid North Carolina review decision for ${row.chargeId}: ${row.decision}`);
  }
  return row;
}

function renderReviewFile(rows: ReviewRow[]): string {
  const entries = rows.map((row) => `  ${quote(row.chargeId)}: {
    chargeId: ${quote(row.chargeId)},
    catalogLabel: ${quote(row.catalogLabel)},
    proposedAlias: ${quote(row.proposedAlias)},
    citation: ${quote(row.citation)},
    subdivision: ${quote(row.subdivision)},
    officialCodeUrl: ${quote(row.officialCodeUrl)},
    approvedDisplayName: ${quote(row.approvedDisplayName)},
    decision: ${quote(row.decision)} as NorthCarolinaAttorneyReviewDecisionStatus,
    reviewer: ${quote(row.reviewer)},
    reviewedAt: ${quote(row.reviewedAt)},
    note: ${quote(row.note)},
  }`).join(",\n");

  return `// Generated from docs/north-carolina-title-attorney-review-completed.csv.
// Do not edit this file directly; regenerate it with:
// npx tsx scripts/data-review/import-north-carolina-attorney-review.ts

import {
  getNorthCarolinaTitleReviewAction,
} from "../../shared/north-carolina-title-review-actions";

export type NorthCarolinaAttorneyReviewDecisionStatus =
  | "approve"
  | "reject"
  | "pending";

export interface NorthCarolinaAttorneyReviewDecision {
  chargeId: string;
  catalogLabel: string;
  proposedAlias: string;
  citation: string;
  subdivision: string;
  officialCodeUrl: string;
  approvedDisplayName: string;
  decision: NorthCarolinaAttorneyReviewDecisionStatus;
  reviewer: string;
  reviewedAt: string;
  note: string;
}

export const NORTH_CAROLINA_ATTORNEY_REVIEW_DECISIONS: Record<
  string,
  NorthCarolinaAttorneyReviewDecision
> = {
${entries}
};

export function getNorthCarolinaAttorneyReviewDecision(
  chargeId: string,
): NorthCarolinaAttorneyReviewDecision | undefined {
  return NORTH_CAROLINA_ATTORNEY_REVIEW_DECISIONS[chargeId];
}

export function isNorthCarolinaAttorneyReviewApproved(
  chargeId: string,
  officialTitle: string,
  citation: string,
  subdivision: string | null = null,
): boolean {
  const decision = getNorthCarolinaAttorneyReviewDecision(chargeId);
  return decision?.decision === "approve" &&
    decision.proposedAlias.trim().toLowerCase() === officialTitle.trim().toLowerCase() &&
    decision.citation.trim().toLowerCase() === citation.trim().toLowerCase() &&
    decision.subdivision.trim().toLowerCase() ===
      (subdivision ?? "Whole section").trim().toLowerCase();
}

export function isNorthCarolinaAttorneyReviewPublishable(
  chargeId: string,
): boolean {
  const decision = getNorthCarolinaAttorneyReviewDecision(chargeId);
  const action = getNorthCarolinaTitleReviewAction(chargeId);
  return (decision?.decision === "approve" || action?.action === "publish") &&
    action?.action !== "hold" &&
    action?.action !== "remove";
}
`;
}

function renderDisplayNames(rows: ReviewRow[]): string {
  const entries = rows
    .filter((row) =>
      row.decision === "approve" &&
      (getNorthCarolinaTitleReviewAction(row.chargeId)?.action ?? "publish") === "publish",
    )
    .map((row) => [
      `  ${quote(row.chargeId)}: ${quote(getNorthCarolinaTitleReviewAction(row.chargeId)?.displayName || row.approvedDisplayName || row.proposedAlias)}`,
      row,
    ]);

  return `// Generated from the attorney-reviewed North Carolina title worksheet.
// This intentionally contains display names only; review notes remain server-side.

export const NORTH_CAROLINA_APPROVED_DISPLAY_NAMES: Record<string, string> = {
${entries.map(([entry]) => entry).join(",\n")}
};

export function getNorthCarolinaApprovedDisplayName(
  chargeId: string,
): string | undefined {
  return NORTH_CAROLINA_APPROVED_DISPLAY_NAMES[chargeId];
}
`;
}

const parsed = parseCsv(fs.readFileSync(inputPath, "utf8"));
if (parsed.length < 2) throw new Error(`No review rows found in ${inputPath}`);
const headers = parsed[0];
const rows = parsed.slice(1).map((values) => asReviewRow(headers, values));
const ids = new Set<string>();
for (const row of rows) {
  if (ids.has(row.chargeId)) throw new Error(`Duplicate North Carolina review row: ${row.chargeId}`);
  ids.add(row.chargeId);
}

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.mkdirSync(path.dirname(displayNamesPath), { recursive: true });
fs.writeFileSync(outputPath, renderReviewFile(rows));
fs.writeFileSync(displayNamesPath, renderDisplayNames(rows));
console.log(`Imported ${rows.length} North Carolina attorney review rows.`);